### ISSUE TITLE
Dandiset-wide visualizations

### ISSUE THREAD

**Issue by pauladkisson** [flatironinstitute/neurosift#104]
Many of the visualizations coming from [MoSeq](https://dattalab.github.io/moseq2-website/index.html) like the characteristic "crowd movies" require loading many sessions simultaneously.  With this in mind, it would be nice if Neurosift could support some kind of Dandiset-wide visualization structure to accommodate requests like these.  I know that Neurosift is still in alpha, so this kind of enhancement may not be an immediate priority, but it could be a very useful extension.

Parallel Issue was raised in NWBWidgets: [catalystneuro/nwbwidgets#310](https://github.com/NeurodataWithoutBorders/nwbwidgets/issues/310)

**Comment by magland** [comment]
Thanks Paul. Yes, I'd like to expand into dandiset-wide visualizations, probably using some sort of scripting or yaml spec to compose the custom figures. Could you describe a minimal example of a visualization that would span more than one NWB file?

**Comment by pauladkisson** [comment]
I would be happy to, but @kaijfox, @wingillis, and/or @calebweinreb would be able to provide more detail/code.  One minimal example would be syllable usage stats: Each animal has a repertoire of behavioral syllables that they use with different frequencies.  These usages are normally computed over many different sessions (and thus many nwb files).

**Comment by magland** [comment]
Thanks Paul. Is there a dandiset I can look at?

**Comment by pauladkisson** [comment]
> Thanks Paul. Is there a dandiset I can look at?

It's still in progress right now (Draft) but this is the one to watch: [000559](https://dandiarchive.org/dandiset/000559)

**Comment by magland** [comment]
Thanks. Here's a [view of a BehaviorSyllable dataset](https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://dandiarchive.s3.amazonaws.com/blobs/898/814/8988143d-3761-4f4a-a20e-368178cb0636&tab=neurodata-item:/acquisition/BehavioralSyllable|LabeledEvents)

![image](https://github.com/flatironinstitute/neurosift/assets/3679296/9cc6bc61-1227-4e44-a4b5-0ea3914e21d9)

and a [position plot](https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://dandiarchive.s3.amazonaws.com/blobs/898/814/8988143d-3761-4f4a-a20e-368178cb0636&tab=neurodata-items:neurodata-item:/processing/behavior/Position/SpatialSeries|SpatialSeries@view:X/Y|/processing/behavior/Position/SpatialSeries)

![image](https://github.com/flatironinstitute/neurosift/assets/3679296/1069f135-df3e-45cd-a13e-9ccaa4013b50)

I'm going to work on the OnePhotonSeries

**Comment by magland** [comment]
Just a note on the chunking of the OnePhotonSeries objects in this dandiset... the chunks are way too small to be able to efficiently load this for visualization in the browser.

```python
import h5py
import remfile

url = 'https://dandiarchive.s3.amazonaws.com/blobs/663/731/66373118-1b68-42c4-bf66-1d253bccbc78'

# open the remote file
f = h5py.File(remfile.File(url), 'r')

# load the neurodata object
X = f['/acquisition/Reference1PSeries']

print(X['data'].chunks)

# Output: (15, 33, 86)
```

**Comment by pauladkisson** [comment]
Thanks for the catch! Will fix

**Comment by pauladkisson** [comment]
@magland, chunks are now 14 full frames (9.55MiB).  Is that sufficiently large for visualizations?

**Comment by magland** [comment]
@pauladkisson Sorry for the delay in reply. Do you have some datasets on dandi that have the new chunking? I can check out to see how the visualization performs.

**Comment by CodyCBakerPhD** [comment]
@magland Those latest DANDI set 59 files also have a raw/processed file split per session, which could additionally constitute a 'dandiset-wide' or other multi-file-per-session-id folder-level approach that could be useful (i.e., viewing the raw acquisition or LFP time series against the behavioral data in the other file)

**Comment by magland** [comment]
> @magland Those latest DANDI set 59 files also have a raw/processed file split per session, which could additionally constitute a 'dandiset-wide' or other multi-file-per-session-id folder-level approach that could be useful (i.e., viewing the raw acquisition or LFP time series against the behavioral data in the other file)

How do you imagine that working from the user's perspective?

**Comment by CodyCBakerPhD** [comment]
> How do you imagine that working from the user's perspective?

Personally I'd prefer some kind of layer that allows navigation of all the files in the DANDI set - similar to how we can currently select multiple data streams to view simultaneously within a single file - which allows me to select multiple files to view simultaneously

That could have two uses cases beyond what @pauladkisson wants

i) select two NWB files that have the same `session_id`/`session_start_time`/`timestamps_reference` and potentially overlapping neurodata objects - takes the union of the two file contents and allows viewing it as if it were a single file, but stored as multiple separate files on DANDI (a lot of users like this pattern so they can easily download all of the lightweight processed data separate from the bulk raw acquisition)

ii) for chronic studies, they often look at how some basic value in a neurodata value changes progressively over sessions, so being able to select a recurring field over several sessions (several NWB files) could prove useful to showing how a trend varies over long timescales (current approach would just be to open multiple neurosift tabs at the same time and move them to different parts of the screen)

**Comment by pauladkisson** [comment]
> @pauladkisson Sorry for the delay in reply. Do you have some datasets on dandi that have the new chunking? I can check out to see how the visualization performs.

This [dandiset](https://dandiarchive.org/dandiset/000559/draft/files?location=sub-HEK293) should have the new chunking.

**Comment by CodyCBakerPhD** [comment]
Status update: this capability is technically possible with explicit neurosift URLs of the form

`https://flatironinstitute.github.io/neurosift/?p=/nwb&url=[first]&url=[second]&url=[third]`

however, two things missing before we can close this: (i) documentation of this for individuals that manually know how to get asset URLs [sorry if this exists and is and I missed it] and/or (ii) a simpler interface for enabling this interaction, such as a neurosift landing page that summarizes/navigates the DANDI archive like how Dendro does it and lets you select the files you want to jointly view

**Comment by magland** [comment]
> interface for enabling this interaction, such as a neurosift landing page that summarizes/navigates the DANDI archive like how Dendro does it and lets you select the files you want to jointly view

I agree. Neurosift should have a dandiset view. I'm putting that on my todo list.

**Comment by magland** [comment]
@CodyCBakerPhD There is now a dandiset page. You can reach that by clicking the dandiset link in the top left part of the nwb page window. It allows browsing of the dandiset assets, just like in dendro. You can select one or more assets and open them in the nwb page.

For example: https://flatironinstitute.github.io/neurosift/?p=/dandiset&dandisetId=000728&dandisetVersion=draft

I think it would be nice if we could ultimately link to this from dandiarchive.

**Comment by CodyCBakerPhD** [comment]
> I think it would be nice if we could ultimately link to this from dandiarchive.

So like a top-level 'Open in neurosift' link from dandiset landing pages? That would be a good request

Otherwise I think the absolute easiest way would be if there's a 'home' button on neurosift itself when viewing assets or a dandiset and that takes you back to a top-level where you can select and browse available dandisets (which have NWB assets)

So I'd also request a top-level dandiset selector for that - again, just like dendro has would be fine

**Comment by magland** [comment]
> Otherwise I think the absolute easiest way would be if there's a 'home' button on neurosift itself when viewing assets or a dandiset and that takes you back to a top-level where you can select and browse available dandisets (which have NWB assets)

@CodyCBakerPhD Thanks for that suggestion!

The [home page of neurosift](https://flatironinstitute.github.io/neurosift) now is a DANDI browser.

**Comment by CodyCBakerPhD** [comment]
Awesome! Looks and feels great

This can now be closed
