### ISSUE TITLE
PSTH grouped on non-categorical column

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#107]
<img width="1724" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/7ca5746c-e573-4aac-9362-1c9efb16fd97">

It is currently possible to group PSTH on a non-categorical column. Here, I am grouping based on RT, reaction time, which is continuous, so the groups are very small and the PSTH is awkward. @magland how are you determining which columns to make available for grouping? Is there any logic to exclude continuously valued columns?

https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://dandiarchive.s3.amazonaws.com/blobs/d0c/495/d0c495db-37d5-4257-90d4-ff22847921fa

**Comment by magland** [comment]
@bendichter I don't think I restrict it at all. Do you have a suggestion for how to determine whether it's categorical? Count the number of unique values?

**Comment by bendichter** [comment]
@magland here is what I use in NWB Widgets, though I will admit it's a bit of a hack:

https://github.com/NeurodataWithoutBorders/nwbwidgets/blob/9885afc44083dda78b3f0fbadf00dfd92aaed455/nwbwidgets/utils/dynamictable.py#L23

**Comment by magland** [comment]
Okay, I implemented a similar logic for picking out the categorical columns. One difference is that I still include columns with only one category... I don't think there's a problem with that.
