### ISSUE TITLE
[CI] Remove project action

### ISSUE THREAD

**Issue by CodyCBakerPhD** [flatironinstitute/neurosift#111]
I notice you don't have a secret set to a GitHub API token that has org project permissions with flatiron

As such you can remove https://github.com/flatironinstitute/neurosift/blob/main/.github/workflows/add-to-dashboard.yml since it won't do any good without it

**Comment by magland** [comment]
Thanks, I have removed the file. I was not able to get it to work properly, but it's okay, because I have manually been adding issues to the project, and that has been working well.
