### ISSUE TITLE
[Question] display ImageSeries transposed

### ISSUE THREAD

**Issue by weiglszonja** [flatironinstitute/neurosift#116]
There is something I noticed, the [OnePhotonSeries](https://pynwb.readthedocs.io/en/stable/pynwb.ophys.html#pynwb.ophys.OnePhotonSeries) data looks rotated and I think it is because imaging data in NWB should be stored width by height (x, y, as described [here](https://pynwb.readthedocs.io/en/stable/pynwb.ophys.html#pynwb.ophys.OnePhotonSeries) but this applies to any image data as well) but `imshow` would expect the order of y and x. Would it be possible to add transpose option or just transpose it by default?

**Comment by CodyCBakerPhD** [comment]
+1 for a little rotation button to flip images (not just OnePhotonSeries, but any Image or ImageSeries decendent) by 90 degrees (two buttons I suppose, to allow user to decide direction of rotation...) to achieve the view they want

Sometimes the view is rectangular, or sometimes even in a square image the object of interest is oblong and a user might want to orient a visual of it in some preferred way irrespective of how it is stored in the file

**Comment by magland** [comment]
@weiglszonja 
It's difficult for me to keep track of examples of various views. Is there a public dandiset you could point to that has an image that is oriented incorrectly? It will be pretty easy to change the default and/or add a button as @CodyCBakerPhD suggests.

**Comment by CodyCBakerPhD** [comment]
> Is there a public dandiset you could point to that has an image that is oriented incorrectly?

I think the one Szonja is working on is this one, embargoed on staging (added you to it)

[https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://api-staging.dandiarchive.org/api/assets/d9f30019-e8ab-43e3-af8d-a5334c415349/download/&dandisetId=210944&dandisetVersion=draft&tab=neurodata-item:/acquisition/OnePhotonSeriesBlue|OnePhotonSeries](https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://api-staging.dandiarchive.org/api/assets/d9f30019-e8ab-43e3-af8d-a5334c415349/download/&dandisetId=210944&dandisetVersion=draft&tab=neurodata-item:/acquisition/OnePhotonSeriesBlue|OnePhotonSeries)

She's also putting together demo tutorials/notebooks for the lab so getting those perfectly in sync with apearances is likely the concern

Another public example would be

https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://dandiarchive.s3.amazonaws.com/blobs/7e3/e07/7e3e0785-4793-4d7f-b07a-bb2d63b127f2&dandisetId=000350&dandisetVersion=0.221219.1506&tab=neurodata-item:/acquisition/TwoPhotonSeries|TwoPhotonSeries

If I wanted to orient it in a different way to match a figure from their paper, for example

**Comment by magland** [comment]
There are now 3 new checkboxes in the bottom menu bar for those views: xy swap, x flip, and y flip

![image](https://github.com/flatironinstitute/neurosift/assets/3679296/684a7abb-7eb2-4638-9d3e-7b309ecf0ac5)
