### ISSUE TITLE
Display PSTH widget when a units table is included in processing/ecephys

### ISSUE THREAD

**Issue by CodyCBakerPhD** [flatironinstitute/neurosift#117]
A part of the workflow being developed via dendro is to write intermediate spike sorting results to `processing/ecephys` in the NWB file

But the PSTH widget (which is amazing!) doesn't seem to recognize any units tables when they are not in the final place (`nwbfile.units`)

Would be cool to enable selection of the units table from the PSTH, and have the PSTH widget be selectable whenever there's at least one unit table in the file

Also there might be a related issue to displaying other units table info such as raster plots (when the table is in processing instead of the final location), see this example below

[https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://api.dandiarchive.org/api/assets/1036fae9-3e36-4693-afa3-939aa56d8aba/download/&dandisetId=000620&dandisetVersion=draft&tab=neurodata-items:view:DirectRasterPlot%7C/processing/ecephys/units@neurodata-item:/processing/ecephys/units%7CUnits](https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://api.dandiarchive.org/api/assets/1036fae9-3e36-4693-afa3-939aa56d8aba/download/&dandisetId=000620&dandisetVersion=draft&tab=neurodata-items:view:DirectRasterPlot%7C/processing/ecephys/units@neurodata-item:/processing/ecephys/units%7CUnits)

**Comment by magland** [comment]
I fixed that issue about the raster plot not showing up for that example.

Yes, we should support PSTH for the case of the units in other locations. But to be consistent with the pattern of the other visualizations, I think this should require that the user select the units table first, and then the PSTH option shows up.

**Comment by CodyCBakerPhD** [comment]
Sure, that makes sense too

It also occurred to me that stimulus timestamps (not just time interval tables) might also be really useful to align, average, and categorize by (if multiple presentations of same stimulus)

Uploading a dandiset just like this for visual coding from the Allen institute right now: https://dandiarchive.org/dandiset/000728

**Comment by magland** [comment]
Partially addressed here:

https://github.com/flatironinstitute/neurosift/issues/119#issuecomment-1866839827

**Comment by CodyCBakerPhD** [comment]
Works for me!

Not quite as intuitive as the previous approach, but I can see how it generalizes better (include selection of things that aren't even units tables, like RoiResponseSeries...)

This learning curve could be fixed by always having a "Open PSTH for selected items" display present but greyed out with an info popup upon hover (or info icon nearby)

Or documentation, but if you started official docs for stuff like that it might get to be a chore to keep it maintained
