### ISSUE TITLE
Trouble viewing rasters and PSTHs

### ISSUE THREAD

**Issue by nwatters01** [flatironinstitute/neurosift#119]
I'm new to Neurosift and am trying to view rasters and PSTHs.

I have a table of units [here](https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://api.dandiarchive.org/api/assets/2fd8e177-ecf6-4d7f-aec4-387da092a4de/download/&dandisetId=000620&dandisetVersion=draft&tab=neurodata-items:neurodata-item:/processing/ecephys/units|Units@view:DirectRasterPlot|/processing/ecephys/units@view:RasterPlot|/processing/ecephys/units@view:Autocorrelograms|/processing/ecephys/units) and a table of trials [here](https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://api.dandiarchive.org/api/assets/2fd8e177-ecf6-4d7f-aec4-387da092a4de/download/&dandisetId=000620&dandisetVersion=draft&tab=neurodata-item:/intervals/trials|TimeIntervals).  I would like to view raster plots and/or PSTHs of some units aligned to trial events (e.g. "trial_start" or "phase_stimulus_time").

Is this possible?  In the units tab I see an option "Request raster plot", but that doesn't seem to load anything when I click on it.

Thank you!

**Comment by CodyCBakerPhD** [comment]
Source of trouble is the request from https://github.com/flatironinstitute/neurosift/issues/117

Units table is in processing instead of the outer level, but that is unrecognized by the PSTH plugin

**Comment by magland** [comment]
@nwatters01 The "request raster plot" option is no longer functional... so I need to remove it.

The links don't work for me -- is this an embargoed dataset?

As Cody says, I think this will be resolved with #117, but I don't think I'll be able to get to that until the beginning of 2024.

**Comment by CodyCBakerPhD** [comment]
> The links don't work for me -- is this an embargoed dataset?

It's 000620 - you've been added to it for a while, just make sure to set your API keys

**Comment by magland** [comment]
@nwatters01 @CodyCBakerPhD I decided to go ahead and address this before vacation. :)

Starting with your dataset (thanks for giving me temporary access Cody)
https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://api.dandiarchive.org/api/assets/2fd8e177-ecf6-4d7f-aec4-387da092a4de/download/&dandisetId=000620&dandisetVersion=draft

First select the two items with checkboxes (units and trials table) as shown

![image](https://github.com/flatironinstitute/neurosift/assets/3679296/80b0c357-01c8-4054-bece-13f4c5559cdc)

Then click on "Open PSTH for selected items" which should appear on the left.

Then you get this

![image](https://github.com/flatironinstitute/neurosift/assets/3679296/70793398-4cf1-46fc-a37f-8855e384800c)

**Comment by nwatters01** [comment]
Amazing, thank you so much!  I just tested and it works great!
