### ISSUE TITLE
Visual striation for large table columns

### ISSUE THREAD

**Issue by CodyCBakerPhD** [flatironinstitute/neurosift#121]
An example: https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://api.dandiarchive.org/api/assets/58703c97-c0a9-4736-b684-73c85c1a444a/download/&dandisetId=000021&dandisetVersion=draft&tab=neurodata-item:/intervals/drifting_gratings_presentations|TimeIntervals

This table has a very large number of columns, and without some sort of visual striation and/or greater distance between the columns, it becomes very difficult to tell values on neighboring columns apart

**Comment by CodyCBakerPhD** [comment]
(by visual striation I just mean some level of different shading from light grey to dark grey)

**Comment by magland** [comment]
Is this what you are seeing?

![image](https://github.com/flatironinstitute/neurosift/assets/3679296/c7ada7f5-b74c-4734-9156-cef33146c63a)

I can tell which columns are which. Could you be more specific on what you are proposing? Alternating column colors, like the way the rows are altnerating?

**Comment by CodyCBakerPhD** [comment]
> I can tell which columns are which.

Explicitly, the amount of effort it takes to differentiate the 'orientation' from the 'spatial_frequency' on line 60 is more than it ought to be, and gets worse at small screen sizes

![image](https://github.com/flatironinstitute/neurosift/assets/51133164/f255e09e-e80c-443e-9fe4-77313ce33f57)


> Could you be more specific on what you are proposing?

> (by visual striation I just mean some level of different shading from light grey to dark grey)

Explicitly, column index 0 have light grey background, index 1 darker grey, index 2 back to light grey, etc.

**Comment by CodyCBakerPhD** [comment]
> Alternating column colors, like the way the rows are altnerating?

I can't actually tell that the rows are alternating at all on my side, are they supposed to be?

**Comment by magland** [comment]
Oh you mean the column labels?

**Comment by CodyCBakerPhD** [comment]
> Oh you mean the column labels?

The entire column, including the name, and the values below it

Look at the example below; if reading the content inside the red box, it takes a fair amount of effort to mentally align the value to its column above because the column names are so smushed together; the small whitespace buffer between values on the same row is likewise easy to miss the cluttered the table becomes. Even just having vertical lines would help

![image](https://github.com/flatironinstitute/neurosift/assets/51133164/bc69cfd9-93b8-4057-bfd8-8f12c72075ad)

**Comment by magland** [comment]
I made changes to the table layout. Added some space between columns and disabled wrapping. What do you think?

![image](https://github.com/flatironinstitute/neurosift/assets/3679296/9b3555d3-f2fb-463c-ae3b-af940b4b186c)

**Comment by magland** [comment]
The coloration by row IS alternating, white to light gray. Maybe you are not able to see it? I can darken the gray (or should I use a different color?)

**Comment by magland** [comment]
I'm not great with colors. How about this?

![image](https://github.com/flatironinstitute/neurosift/assets/3679296/b672b99c-2bd0-416f-bcfb-c7fbce710702)

**Comment by CodyCBakerPhD** [comment]
Aha, got to the bottom of it!

The greys only render under certain monitor settings (and is blank white otherwise, leading to all this confusion); but the green looks great on all devices

**Comment by magland** [comment]
Okay good. Green will be deployed as soon as gh pages builds.

**Comment by CodyCBakerPhD** [comment]
Looking better! Closing for now

Another good test reference for this is https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://api.dandiarchive.org/api/assets/c7086afe-8e33-4f08-a7f1-b745ad8e2c48/download/&dandisetId=000409&dandisetVersion=draft&tab=view:Units|/units
