### ISSUE TITLE
Left summary window clips long text

### ISSUE THREAD

**Issue by CodyCBakerPhD** [flatironinstitute/neurosift#124]
It's not unusual to have very long experiment descriptions or notes

The left summary bar is fantastic to have; but I notice it clips text at a hard cutoff, even if I expand it

![image](https://github.com/flatironinstitute/neurosift/assets/51133164/d954bd2e-9ded-4acf-8b9d-1dcf606827a0)

Would it be possible to wrap text instead into a taller box? It wouldn't have to be very large to fit at most a few paragraphs

**Comment by magland** [comment]
This used to wrap... but there was an unintended global consequence of the last table layout tweak. So I fixed it and it should be deployed shortly.

**Comment by CodyCBakerPhD** [comment]
Looks like it's wrapping again - thanks!
