### ISSUE TITLE
[Feature] Compatibility with CHANGES file

### ISSUE THREAD

**Issue by CodyCBakerPhD** [flatironinstitute/neurosift#127]
@colleenjg has been pushing forward some changes to DANDI that allow attachment of a changelog for mutliple version releases

On top of the dandiset-level view through neurosift possible from #104, it would be great if neurosift could actively render the text of these files (all I can do on the dandi side is download the file, which seems silly for a 400 byte file)

https://dandiarchive.org/dandiset/000037/0.240209.1623/files?location= is the first example of this (scroll down to bottom; see the CHANGES file), though I will likely make more personal use of it from now on as well

**Comment by colleenjg** [comment]
Yes, I agree! Thanks for pointing that out @CodyCBakerPhD

**Comment by magland** [comment]
Cool. So I'd look for an asset named "CHANGES" and display the contents?

**Comment by CodyCBakerPhD** [comment]
Yep; pretty easy ^.^

**Comment by magland** [comment]
How's this? 
https://flatironinstitute.github.io/neurosift/?p=/dandiset&dandisetId=000037&dandisetVersion=0.240209.1623
Scroll to the bottom

**Comment by CodyCBakerPhD** [comment]
Beautiful ❤
