### ISSUE TITLE
PSTH: control features of Group By features

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#133]
<img width="1166" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/8c08b592-da0d-49a8-b78f-36c8a0154b47">

In the above graph, -1 means a left choice, 1 means a right choice, and 0 means a mistake trial. The 0 trials are making the view messy and are distracting. This is an example of a situation where it would be quite helpful to be able to sub-select specific features of the Group By column. My preferred solution would be to have it so that when you select a Group By option, a new box appears with all of the unique values of that column, pre-selected by default. Then a user could choose to de-select columns they don't want to see in the PSTH plot.

**Comment by magland** [comment]
Sounds reasonable, but I feel like there's no room for that in the control panel. Where do you think it should go?

https://flatironinstitute.github.io/neurosift/?p=/nwb&dandisetId=000688&dandisetVersion=draft&url=https://api.dandiarchive.org/api/assets/9ac13aea-5d1c-4924-87b4-40ef0a3555d8/download/&tab=view:PSTH|/intervals/trials

![image](https://github.com/flatironinstitute/neurosift/assets/3679296/2ab0ed08-dc09-4d48-bfa8-1057cc97474d)

**Comment by bendichter** [comment]
We could put it within an accordion under the Group by dropdown

**Comment by magland** [comment]
@bendichter

There is now an "Advanced" button at the bottom of the prefs panel - it opens a larger window where you can select categories as you suggested.

The difficulty in the layout is that the bottom section is a fixed height, so even with an accordion it's not easy to fit it inline in a sensible way.

**Comment by bendichter** [comment]
@magland looks like it works for the most part, but has some issues with NaN

https://github.com/flatironinstitute/neurosift/assets/844306/ddd9ffc5-9559-4c3c-b22b-b62a3ee2d6fb

**Comment by magland** [comment]
Could you provide a link to that example so I can try to reproduce?

**Comment by bendichter** [comment]
@magland it was the link you provided above: https://flatironinstitute.github.io/neurosift/?p=/nwb&dandisetId=000688&dandisetVersion=draft&url=https://api.dandiarchive.org/api/assets/9ac13aea-5d1c-4924-87b4-40ef0a3555d8/download/&tab=view:PSTH%7C/intervals/trials

**Comment by magland** [comment]
This should be fixed now.

**Comment by bendichter** [comment]
Yup, this is working now. Thanks!
