### ISSUE TITLE
rendering many-neuron raster plots

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#137]
e.g. https://neurosift.app/?p=/nwb&url=https://api.dandiarchive.org/api/assets/1d0901e5-80a7-491e-95b6-758d8320d350/download/&dandisetId=000302&dandisetVersion=draft&tab=view:DirectRasterPlot|/units&tab-time=0.6095928682714352,2819.3642157881454,664.666486238638

Two issues here:
1. There is a message "Showing 246 of 580 units" only displays when the field of view is too large to view any neurons. When you zoom in you can start to see neurons, but the message goes away. Anyone who does not zoom out might think they are looking at activity from all of the neurons.
2. There is no way to change which neurons are in view. It would be nice if you could move "up and down" in this view to see the other 334 neurons, perhaps in windows of 200. This would ideally also be depicted as a window view similar to the time window viewer, but vertical and showing the window of unit IDs you are viewing.

**Comment by magland** [comment]
@bendichter I changed the layout and there are now some buttons that let you navigate through the units, and also increase or decrease the number of units visible.

![image](https://github.com/flatironinstitute/neurosift/assets/3679296/a3e09d65-7345-4c1c-80dc-6b9283d991c0)

**Comment by bendichter** [comment]
Thanks! This gets the job done. We can leave making the controls a bit friendlier as a future direction.
