### ISSUE TITLE
Cache dandisets listings

### ISSUE THREAD

**Issue by yarikoptic** [flatironinstitute/neurosift#138]
ATM dandiarchive experiencing problems due to one endpoint - listing of assets being "heavy":

- https://github.com/dandi/dandi-archive/issues/1891

neurosift already does a good thing imho by using max page size allowed (`page_size=1000`) so ATM it takes just a few seconds to get first `10,000`  assets for 000026, related 

- https://github.com/dandi/dandi-archive/issues/1907

but I wonder if it would be possible to cache those listings on client side to avoid re-requesting at all?

also - you could use 

![image](https://github.com/flatironinstitute/neurosift/assets/39889/8e57737d-913e-47bd-96bb-81655ec296ff)

endpoint for more efficient/less aggressive navigation of the dandisets.

**Comment by magland** [comment]
I did something related, but not what you are asking for. Maybe this will be sufficient. Neurosift now only requests a single page and presents a warning and asks if user wants to retrieve more pages. I think most of the time, the user is just visiting the dandiset and will not request multiple pages. See

https://neurosift.app/?p=/dandiset&dandisetId=000728&dandisetVersion=draft

Does that do the trick, or do you want me to also implement client-side caching (which is a bit annoying to have to manage, especially with paging).

**Comment by yarikoptic** [comment]
I think that is great and sufficient overall for now. Paired with 
- https://github.com/flatironinstitute/neurosift/issues/139
should be comprehensive  solution to help ensuring absent bombardment of DANDI even whenever neurosift will be ran on all microway appliances ;) (exaggerating but do hope it would become a problem some time ;) ).  Thank you!  Let's close
