### ISSUE TITLE
better NWB file exploration

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#14]
We just recently added to HDMF a feature to generate HTML for NWB objects that allows the user to navigate into NWB files and explore each group, attribute, and dataset within the file in a hierarchical accordion [here](https://github.com/hdmf-dev/hdmf/blob/0c01dd7e83f11a07bc26bbae9975046a963f7e91/src/hdmf/container.py#L463). Could Neurosift do something similar? Specifically, if you click Browse NWB File, you get this view:

![image](https://github.com/flatironinstitute/neurosift/assets/844306/1e6b105c-e30d-4d6c-98fe-2b5bca60818a)

but that does not have any information about e.g. the attributes of ElectricalSeries. See this PR: https://github.com/hdmf-dev/hdmf/pull/883

**Comment by magland** [comment]
@bendichter this has now been implemented

![image](https://github.com/flatironinstitute/neurosift/assets/3679296/c4fc328c-5e26-41ef-a159-3b37787a3b15)

**Comment by bendichter** [comment]
lgtm!
