### ISSUE TITLE
PSTH: redundant x axis labels

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#142]
https://neurosift.app/?p=/nwb&url=https://api.dandiarchive.org/api/assets/2275fcb5-6bbb-409c-8c84-1864a9bd1c32/download/&dandisetId=000947&dandisetVersion=draft&tab=view:PSTH|/intervals/trials&tab-time=undefined,undefined,undefined

<img width="1499" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/b96cb0e3-873e-4ce8-99c9-cddecc696d24">

This is fairly minor, but in the above image, there are two redundant x axis labels, which takes up unnecessary space, particularly when Heigh is set to Small. I think it would be better to keep the bottom xtick labels and xlabel "Time offset (s)" but to remove the xticks and xlabel in the upper plot, putting these axes in a "sharex" mode in matplotlib lingo. This could only be done when both the raster and the histogram are displayed.

**Comment by magland** [comment]
Done
