### ISSUE TITLE
No plugin for FilteredEphys

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#144]
<img width="1536" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/e33de791-6229-4218-8618-e83cbbeee944">

https://neurosift.app/?p=/nwb&url=https://api.dandiarchive.org/api/assets/2275fcb5-6bbb-409c-8c84-1864a9bd1c32/download/&dandisetId=000947&dandisetVersion=draft

FilteredEphys holds ElectricalSeries and should have the exact same visualization as LFP

**Comment by bendichter** [comment]
<img width="762" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/c5c6160d-8325-4d94-81ec-f32026d2c051">

**Comment by bendichter** [comment]
fyi @weiglszonja

**Comment by magland** [comment]
Done.
