### ISSUE TITLE
Datasets not loading in Raw mode

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#146]
Error opening datasets in Raw view:

https://neurosift.app/?p=/nwb&url=https://api.dandiarchive.org/api/assets/80be44d6-db90-4807-bb1b-abdac5c580eb/download/&dandisetId=000727&dandisetVersion=0.240106.0043

https://github.com/flatironinstitute/neurosift/assets/844306/ea73f1d1-b541-492e-a7ad-32467981e1f0

**Comment by magland** [comment]
Strange, I am not able to reproduce. I tried both on chrome and on firefox. Could you try again and let me know what browser you are using?

![image](https://github.com/flatironinstitute/neurosift/assets/3679296/72318320-5105-485c-a43b-5fe0900e7755)

**Comment by bendichter** [comment]
Works for me now. I'll close.
