### ISSUE TITLE
Neurosfit over http

### ISSUE THREAD

**Issue by arnodelorme** [flatironinstitute/neurosift#147]
I am getting this error when trying to see a local file. The issue is that the file is not served through HTTPS while neurosift is on HTTPS. Any way to fix that issue? Tx

<img width="1629" alt="Screenshot 2024-04-12 at 3 53 36 PM" src="https://github.com/flatironinstitute/neurosift/assets/1872705/78ca17a4-161c-4a9c-95c8-eb31ddd5e042">

**Comment by magland** [comment]
Is the url on localhost?

What browser are you using? I believe chrome allows http if it's on localhost.

**Comment by arnodelorme** [comment]
I used the command "python -m http.server" on a local folder.

**Comment by CodyCBakerPhD** [comment]
Have you tried to use the local file visualization feature of the [NWB GUIDE](https://nwb-guide.readthedocs.io/en/latest/installation.html) desktop application?

I wonder if that might make it easier (it uses Neurosift, but automates some of those details like setting up the serve yourself and controls the browser rendering as well)

**Comment by arnodelorme** [comment]
Thanks. I was talking to Yaroslav that told me to submit an issue just in case you have a solution. We want to test the use of Neurosift for NEMAR (the OpenNeuro mirror for MEEG data), and assess if it works well to stream data.

This issue is not too important. I can, in time, make sure my file is served through HTTPS. I will probably get back to you with more questions. Tx.

**Comment by magland** [comment]
@arnodelorme Another possibility is to run a local dev version of neurosift, which would run over http on localhost.

**Comment by arnodelorme** [comment]
Good point @magland. One question we have about NeuroSift is whether it is possible to fine tune the URL parameters to directly show one of the ElectricalSeries along with the intervals_trials event information. Our users will not know how to navigate the "annotation" and other tabs to plot that information -- to tell the truth, even though Ben showed it to me yesterday (both Ben and Yaroslav were at the BIDS derivative meeting in Seattle), I was not able to reproduce it on my own :-). Also, I built a NWB importer/exporter for EEGLAB https://github.com/arnodelorme/nwbio so we can test your viewer with NEMAR (plus it will be useful for iEEG researchers which we support).
