### ISSUE TITLE
Feature request: Ability to reorder PSTHs by selectivity

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#148]
In some Dandisets we have PSTHs of 1000s of units.

https://neurosift.app/?p=/nwb&url=https://api.dandiarchive.org/api/assets/b305ccec-fa84-445e-aea5-0126d6eff558/download/&dandisetId=000253&dandisetVersion=draft&tab=view:PSTH|/intervals/create_receptive_field_mapping_presentations

With so many units, it can be laborious to look through these units to find the most interesting ones. It would be nice if we had a basic statistical test that allowed us to optionally reorder units so the ones that differentiate the category of interest most are first. We could put this in the Advanced section so it does not clutter the interface.

**Comment by magland** [comment]
A couple issues here. First is figuring out what statistical test to use -- and that is going to depend on which variables are selected. Second is the computation/download time. Right now the data are downloaded lazily per unit -- I think it will be very time-consuming to download all of the data in order to make this computation -- at least in the example you shared. This might be something that is better performed in a Python script outside the browser...

**Comment by CodyCBakerPhD** [comment]
Can you currently filter/order the PSTH widget by some other column of the Units column?

These can oftentimes be quality metrics, including possibly a custom field that a user creates (or NeuroConv/SI creates for them) representing a 'PSTH quality score' as imagined in this issue - that way you could be general about it and offload computation concerns to the file contents

Example on IBL: https://neurosift.app/?p=/nwb&url=https://api.dandiarchive.org/api/assets/37e571e6-cab5-4777-ac07-bffca527255e/download/&dandisetId=000409&dandisetVersion=draft

the 'label' property (proportion of quality metrics passed)

**Comment by magland** [comment]
@CodyCBakerPhD That sounds doable. I'll see what I can put together.

**Comment by magland** [comment]
Okay, there is now a "sort units by" selector in the advanced options

![image](https://github.com/flatironinstitute/neurosift/assets/3679296/6f3f9989-60b1-466d-9cfd-5205e577b381)

**Comment by CodyCBakerPhD** [comment]
Awesome! Someone should think of some potential PSTH-relaated quality metrics (scalars) that could go into SI or somewhere else for this purpose

Just to put the idea in your head to imagine a more general UX that could work - how about joint filters, such as 'greater than 0.01 Hz firing rate && contamination ratio less than 0.5'?

**Comment by bendichter** [comment]
Nice!
