### ISSUE TITLE
Unexpected neurodata_type: Image

### ISSUE THREAD

**Issue by CodyCBakerPhD** [flatironinstitute/neurosift#151]
https://neurosift.app/?p=/nwb&url=https://api.dandiarchive.org/api/assets/f02db27e-82eb-41dd-865a-a08bb41491da/download/&dandisetId=000728&dandisetVersion=draft&tab=neurodata-item:/processing/ophys/SummaryImages|Images

![Screenshot 2024-04-16 at 10 14 11 AM](https://github.com/flatironinstitute/neurosift/assets/51133164/80fcb662-3880-4e3a-bc64-d2dce335e862)

**Comment by magland** [comment]
Working now!

![image](https://github.com/flatironinstitute/neurosift/assets/3679296/32e89947-e3f2-4e06-88c6-26df89b1313b)

**Comment by CodyCBakerPhD** [comment]
Can you add the same kind of flipping/rotation buttons as are on other view like (like TwoPhotonSeries I think?)

Technically this image is upside down from what the original view was intended to be

**Comment by magland** [comment]
@CodyCBakerPhD 
I made the adjustment it in the code (I saw where the error was). I am not going to add the flip/rotate buttons at this point for this view. But we can revisit if there is another example that is problematic.

![image](https://github.com/flatironinstitute/neurosift/assets/3679296/152b2e4b-155b-4428-b975-fe211c0817ce)

**Comment by CodyCBakerPhD** [comment]
Moved rotation request to #155 

Original problem here resolved
