### ISSUE TITLE
DF/F RoiResponseSeries fails on transition from 10 to 20 channel selections

### ISSUE THREAD

**Issue by CodyCBakerPhD** [flatironinstitute/neurosift#152]
https://neurosift.app/?p=/nwb&url=https://api.dandiarchive.org/api/assets/f02db27e-82eb-41dd-865a-a08bb41491da/download/&dandisetId=000728&dandisetVersion=draft&tab=neurodata-items:neurodata-item:/processing/ophys/DfOverF/DfOverF|RoiResponseSeries@neurodata-item:/processing/behavior/BehavioralTimeSeries/running_speed|TimeSeries

10 works great

<img width="1708" alt="Screenshot 2024-04-16 at 10 42 54 AM" src="https://github.com/flatironinstitute/neurosift/assets/51133164/c20d8b52-8205-428d-89e0-9cce90529522">

Change it to 20 and nothing renders at all

<img width="1711" alt="Screenshot 2024-04-16 at 10 43 28 AM" src="https://github.com/flatironinstitute/neurosift/assets/51133164/958f5b39-c108-4a56-b30c-0bd3c53d8a86">

I chunked these at ~10MB, a corresponding data selection streams very quickly in Python

**Comment by CodyCBakerPhD** [comment]
No errors in console that I can see either, and doesn't matter how long I wait

**Comment by magland** [comment]
@CodyCBakerPhD I think you just need to zoom in as the message says. This is to prevent excessive data loading. There's also a way to override that protection - click the ? button.

**Comment by CodyCBakerPhD** [comment]
Zooming in time more did the trick!

> There's also a way to override that protection - click the ? button.

That just leads to

<img width="466" alt="Screenshot 2024-04-16 at 11 32 10 AM" src="https://github.com/flatironinstitute/neurosift/assets/51133164/34847f2c-dbf2-4ac6-bbc2-d5896576bba5">

**Comment by magland** [comment]
I meant the other question mark :)

on the left tool panel for the timeseries view
