### ISSUE TITLE
Special characters in `experiment_description` not rendering

### ISSUE THREAD

**Issue by weiglszonja** [flatironinstitute/neurosift#161]
hey @magland! I noticed in this [file](https://neurosift.app/?p=/nwb&dandisetId=000947&dandisetVersion=draft&url=https://api.dandiarchive.org/api/assets/96246b9d-d27d-45d8-bd91-8b90f18fcf44/download/) the special characters are not rendering correctly.
I also have an embargoed dandiset with this experiment description that looks correctly when opening in neurosift. 
Can you take a look?

**Comment by weiglszonja** [comment]
I'm using Safari:
<img width="988" alt="Screenshot 2024-04-24 at 16 07 29 (2)" src="https://github.com/flatironinstitute/neurosift/assets/24475788/92dd91ce-a2a3-4f24-9374-c9c21ef02b42">

**Comment by CodyCBakerPhD** [comment]
Platform might also make a slight difference to how the boxes/question marks render

Here is windows chrome

![image](https://github.com/flatironinstitute/neurosift/assets/51133164/55109877-29a7-42d3-aa51-a5e680022cc6)

**Comment by magland** [comment]
Thanks @weiglszonja . I have tracked the issue down to a problem with how neurosift decodes a dataset of type <Uxx. Working on a fix.

**Comment by magland** [comment]
Should be working now

![image](https://github.com/flatironinstitute/neurosift/assets/3679296/d7dcb822-a542-4b2a-ab4e-b75630547266)

**Comment by weiglszonja** [comment]
Thanks @magland, looks great!
