### ISSUE TITLE
PSTH widget: choose combination of Units and Intervals tables

### ISSUE THREAD

**Issue by luiztauffer** [flatironinstitute/neurosift#162]
It would be good to be able to select the source `Units` and `Intervals` table to be used in the PSTH widget.
The necessity emerges when we have multiple of these, most likely multiple Units tables resulting from Dendro jobs

![image](https://github.com/flatironinstitute/neurosift/assets/24541631/85ca34d0-bda1-46b7-937d-690e7c9b816f)

**Comment by magland** [comment]
This is already possible. Select the two items (checkboxes) and then a link appears in left panel "Open PSTH for selected items"

![image](https://github.com/flatironinstitute/neurosift/assets/3679296/9af70e58-dc61-48e4-aa50-5ad121bd0b3b)

**Comment by luiztauffer** [comment]
oh, perfect!
