### ISSUE TITLE
Color of raster when selecting units in waveform widget

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#163]
It's very cool to see the linking between waveform and raster! I just have a minor gripe: when you are selecting units in the waveform widget, the entire raster turns blue and it is hard to see. When you hover over the raster, the color changes to black with a blue highlight for the selected units - this looks great. Would it be possible to have it so that this coloring is used also while selecting units on the waveform widget?

https://github.com/flatironinstitute/neurosift/assets/844306/cfc0efd9-ed1a-4511-9c77-017cd8f6571a

**Comment by bendichter** [comment]
The view looks good when I am hovering over the raster, with timestamps in black and blue highlighting the cells. Could we make it look like that also when the user is not hovering?

**Comment by magland** [comment]
This has been fixed
https://neurosift.app/?p=/nwb&url=https://fsbucket-dendro.flatironinstitute.org/dendro-outputs/dfd624da/dfd624da.6344fd7c/output&url=https://api.dandiarchive.org/api/assets/c04f6b30-82bf-40e1-9210-34f0bcd8be24/download/&tab=neurodata-items:view:DirectRasterPlot|/processing/ecephys/units@view:AverageWaveforms|/processing/ecephys/units

**Comment by bendichter** [comment]
Looks great!
