### ISSUE TITLE
OptogeneticSeries with small amount of data failing

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#165]
https://neurosift.app/?p=/nwb&url=https://api.dandiarchive.org/api/assets/7d1990d7-a714-406e-9cb2-1b8f4015869e/download/&dandisetId=000971&dandisetVersion=draft&tab=neurodata-item:/stimulus/presentation/OptogeneticSeries|OptogeneticSeries&tab-time=0,404.9999999986085,undefined

<img width="1609" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/92a43df3-e0dc-4b37-a713-de47c2e0dac1">

```
Uncaught (in promise) Error: Problem slicing stimulus/presentation/OptogeneticSeries/timestamps: i1End > shape[0]: 3000 > 81
    at bv (index-1560e54b.js:253:63141)
    at zk.getDatasetData (index-1560e54b.js:253:68955)
    at async nUA.getTimestampsForDataIndices (index-1560e54b.js:282:61521)
    at async index-1560e54b.js:282:67162
```

**Comment by bendichter** [comment]
cc @pauladkisson

**Comment by magland** [comment]
This has been fixed. (and you need to zoom out to see it, but that wasn't the problem)

**Comment by bendichter** [comment]
@pauladkisson, is this what you intended it to look like?

https://neurosift.app/?p=/nwb&url=https://api.dandiarchive.org/api/assets/7d1990d7-a714-406e-9cb2-1b8f4015869e/download/&dandisetId=000971&dandisetVersion=draft&tab=neurodata-item:/stimulus/presentation/OptogeneticSeries|OptogeneticSeries&tab-time=0,2038.9050000000002,undefined

I think it might help to add 0-amp points at times immediately before each stim time so we get rectangles instead of ramps

**Comment by bendichter** [comment]
@magland an alternative might be to render as steps instead of linear interpolation. The [TimeSeries type](https://nwb-schema.readthedocs.io/en/stable/format.html#sec-timeseries) has a flag "continuity" which could be used to control this.
* The current mode matches "continuous"
* "discrete" would be points but no line connecting them
* "step" would render as a step rather than linear interpolation

**Comment by pauladkisson** [comment]
> I think it might help to add 0-amp points at times immediately before each stim time so we get rectangles instead of ramps

There's a couple problems with this approach, the main one being what time is "immediately before"?  The other problem is that the second 0-amp timepoint carries basically no information so it's pretty inefficient.  That being said, the time series approach in general is a bit inefficient for cases like these that are really more appropriately described an array of onset times and a set of parameters (frequency, amplitude, pulse width, etc.).  At some point it may be worth incorporating this alternative representation into one of the ogen extensions.

> an alternative might be to render as steps instead of linear interpolation.
I think would be the best solution for the near-term.

**Comment by magland** [comment]
Looking back at this, the original issue has been fixed, but I do see that there are some other things to consider. Should I close this and we can open a new issue for figuring out whether/when to do continuous, discrete, and step?

**Comment by bendichter** [comment]
Yes, that sounds good
