### ISSUE TITLE
Time series data during gap

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#166]
https://neurosift.app/?p=/nwb&url=https://api.dandiarchive.org/api/assets/7d1990d7-a714-406e-9cb2-1b8f4015869e/download/&dandisetId=000971&dandisetVersion=draft&tab=neurodata-item:/stimulus/presentation/OptogeneticSeries|OptogeneticSeries&tab-time=1892.208971662217,1998.4332404549616,2037.8374710348946

<img width="1728" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/bef07fa4-5e2a-4864-9e44-729206cbfd6b">

Right now if you view a time region of a TimeSeries where there are no data points, no data appears. I think it would be better to show a line connecting the first point to the left and the first point to the right.

**Comment by bendichter** [comment]
Otherwise you get this strange behavior:

https://github.com/flatironinstitute/neurosift/assets/844306/be8df416-463d-4422-a92c-7602b86c9d60

**Comment by bendichter** [comment]
cc @pauladkisson

**Comment by magland** [comment]
This has been fixed.
