### ISSUE TITLE
populate processing modules dynamically

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#17]
https://github.com/flatironinstitute/neurosift/blob/78ebd843441e6dc53f1ca44eb1f650ec72ceb597/gui/src/pages/NwbPage/NwbMainView/NwbMainView.tsx#L69-L76

The names of processing modules are flexible. The module names of the nwb schema, e.g. "behavior" and "ecephys", are recommended best practices, but users have the ability to create processing modules with any name and often do so.

I would recommend changing this to dynamically generate these headings from the js equivalent of `h5file["/processing"].keys()`

**Comment by magland** [comment]
Fixed. Closing.
