### ISSUE TITLE
Coordinates are not showing up in `DynamicTable` view

### ISSUE THREAD

**Issue by weiglszonja** [flatironinstitute/neurosift#173]
The values in the "coordinates" column in the `FiberPhotometryTable` (which extends `DynamicTable`) is not showing up, example file:
https://neurosift.app/?p=/nwb&url=https://api.dandiarchive.org/api/assets/46e07d79-70a7-4608-a476-61c6fa94a598/download/&dandisetId=001038&dandisetVersion=draft&tab=neurodata-item:/general/FiberPhotometry/FiberPhotometryTable|FiberPhotometryTable
Screenshot:
<img width="1113" alt="Screenshot 2024-06-04 at 10 55 00" src="https://github.com/flatironinstitute/neurosift/assets/24475788/271bcda9-8f01-4c53-a6a5-8d8f1abc58b2">
But it is visible in "raw" view:
<img width="992" alt="Screenshot 2024-06-04 at 10 58 28" src="https://github.com/flatironinstitute/neurosift/assets/24475788/37f690ef-4bea-449d-abcd-e0c503ce5fa0">
Is it possible to fix it?

**Comment by magland** [comment]
Thanks for the report! This should now be fixed.

**Comment by weiglszonja** [comment]
Thanks for the quick fix @magland! 💯
