### ISSUE TITLE
`TimeIntervals` UI overlap

### ISSUE THREAD

**Issue by weiglszonja** [flatironinstitute/neurosift#174]
I noticed a strange behavior when switching from time plot to table view, at first when I opened the table view it looked normal, but if I switch back to time plot and then table, the view overlaps:

File:
https://neurosift.app/?p=/nwb&url=https://api.dandiarchive.org/api/assets/a07e739d-6246-4f76-8649-9a345cfbdda7/download/&dandisetId=001038&dandisetVersion=draft&tab=neurodata-item:/processing/behavior/Events|TimeIntervals
Screenshot:
<img width="1506" alt="Screenshot 2024-06-04 at 11 04 32" src="https://github.com/flatironinstitute/neurosift/assets/24475788/330166ef-b66e-4afc-beae-79d02c80b2b2">

Also the time plot is only showing the "tags" of the `TimeIntervals`, would it be possible to be able to select whether the `tags` or just the `event_type`s are visible on the time plot?

**Comment by weiglszonja** [comment]
hmm it might be a Safari-only bug, I opened this in Google Chrome and it looks fine there. 

> Could you please open that other tags/event_type issue as a separate issue?

Will do

**Comment by magland** [comment]
@weiglszonja Could you check whether this is fixed now on safari, please?

**Comment by weiglszonja** [comment]
Yes it looks good, thank you!
