### ISSUE TITLE
Too long paths hide close button on tabs

### ISSUE THREAD

**Issue by luiztauffer** [flatironinstitute/neurosift#177]
Too long paths names will hide the close button on tabs:

![image](https://github.com/flatironinstitute/neurosift/assets/24541631/ce6e3c59-8c93-46d4-9eda-629ba0e5a04a)

**Comment by magland** [comment]
Would you be able to provide a link to reproduce?

**Comment by luiztauffer** [comment]
it was happening yesterday navigating through the widgets at the url you shared on Slack, but testing it again now, it seems that the whole path name disappeared from the tab, and we're left with just the Object name, which seems to have solved the problem
