### ISSUE TITLE
Documentation or UI: Unclear purpose of raw and default views

### ISSUE THREAD

**Issue by h-mayorquin** [flatironinstitute/neurosift#181]
I have been using neurosift for a while and I still don't understand what is the purpose of each of the windows on the top:

![image](https://github.com/flatironinstitute/neurosift/assets/6429509/96948add-534b-4232-921a-47d3968fedb8)

I think that widgets, specification and annotations are kind of clear enough by themselves but default vs raw is not.

Perhaps a tooltip with the purpose as documentation would be useful?

**Comment by magland** [comment]
I have added tooltips.

**Comment by h-mayorquin** [comment]
The new ones look great. Thanks a bunch!
