### ISSUE TITLE
neurosift cannot open ImageSegmentation object.

### ISSUE THREAD

**Issue by chrisvdt** [flatironinstitute/neurosift#183]
On this nwb file; https://gui-staging.dandiarchive.org/dandiset/214612/draft/files?location=sub-amarone&page=1

neurosift opens all the other objects in the file, but cannot display  /processing/ophys/ImageSegmentation

With HD5View, I compared the file with another nwb file; sub-491604967_ses-496908818-StimB_behavior+image+ophys

Both use a pixel_mask with a pixel_index. The data structure looks identical, however, the second file does show an image of a mask in neurosift.

**Comment by magland** [comment]
Thanks for reporting that bug. It should be working now.

**Comment by chrisvdt** [comment]
Well, I do see an image now, however, there should be 48 rois, but I only see one.
![afbeelding](https://github.com/flatironinstitute/neurosift/assets/5311644/c55fb72d-f504-458b-959c-4e966274c481)

If I import the pixel_image with matnwb, it looks like this;
![afbeelding](https://github.com/flatironinstitute/neurosift/assets/5311644/b14ca386-7ba7-4e6c-9595-fc7e8bb7e69d)

It seems that the dimensions are not the same.

**Comment by chrisvdt** [comment]
@magland Thanks for your help. I've been able to solve this issue. Someone pointed me to the fact that the pixel_mask_index should be cumulative sums of a series of pixels_per_roi. It works now.
