### ISSUE TITLE
pixel range slider for images

### ISSUE THREAD

**Issue by chrisvdt** [flatironinstitute/neurosift#184]
I noticed that the summary images were displayed very dark.  This is because the pixel value range is very large, but the interesting details are in a smaller range of pixel values. It would be nice if there was a slider at the side to set the set a cutoff for the lower and upper pixel values. This would then enable a user to view the image in different ways.

**Comment by bendichter** [comment]
Here is a good example of an image that would benefit from this:

[https://neurosift.app/?p=/nwb&url=https://api.dandiarchive.org/api/assets/120dc453-ad2f-4df2-8dd3-26c2ead322ed/download/&dandisetId=000294&dandisetVersion=draft&tab=neurodata-item:/processing/imaging/confocal|Images](https://neurosift.app/?p=/nwb&url=https://api.dandiarchive.org/api/assets/120dc453-ad2f-4df2-8dd3-26c2ead322ed/download/&dandisetId=000294&dandisetVersion=draft&tab=neurodata-item:/processing/imaging/confocal%7CImages)

**Comment by magland** [comment]
@bendichter that example is hundreds of Megabytes which is difficult to work with, especially with frequent page reloads. Is there a smaller example that has this issue? @chrisvdt

**Comment by chrisvdt** [comment]
Here is a series of images that are not well in range. @Jeremy ***@***.***>

https://neurosift.app/?p=/nwb&url=https://api-staging.dandiarchive.org/api/assets/ecccf03e-bd92-43f8-b0bd-2a60e8ab8429/download/&dandisetId=214612&dandisetVersion=draft

________________________________

**Comment by magland** [comment]
@chrisvdt I added brightness/contrast sliders. How does this look?

https://neurosift.app/?p=/nwb&url=https://api-staging.dandiarchive.org/api/assets/ecccf03e-bd92-43f8-b0bd-2a60e8ab8429/download/&dandisetId=214612&dandisetVersion=draft&tab=neurodata-item:/processing/ophys/SummaryImages|Images

**Comment by chrisvdt** [comment]
This looks much better, thanks,

But do I still not need to reduce or normalize the image pixel range before saving to an nwb file?

---------------------------------------------------
Dr. C. van der Togt

Data manager
Netherlands Institute for Neuroscience
Meibergdreef 47
1105BA Amsterdam
The Netherlands

**Comment by magland** [comment]
> But do I still not need to reduce or normalize the image pixel range before saving to an nwb file?

Not sure I understand that question. Could you explain a bit more?

**Comment by magland** [comment]
Closing since the original request has been solved, but feel free to reopen.
