### ISSUE TITLE
Change/Customizing Plotting Options

### ISSUE THREAD

**Issue by tabedzki** [flatironinstitute/neurosift#185]
When plotting, especially, in spatial series, can we allows for the following types of options: 
- [ ] An option to disable the horizontal line on the bottom of the figure or to make it lighter/differentiated from the other lines? 
    - If one zooms in a lot (talking x-range being 10ms wide), it can be hard to distinguish between a mouse staying very close to the starting position and the horizontal line on the bottom.
- [ ] When plotting multiple channels, an option to colorize the separate channels/lines

Thank you in advance

**Comment by magland** [comment]
Hi @tabedzki, this is pretty straightforward, but I probably won't be able to get to it until after the 22nd. If it's still needed at that time it would be helpful if you could bump this issue, if you don't mind.

**Comment by tabedzki** [comment]
Sounds good. I'll set a reminder.

**Comment by tabedzki** [comment]
@magland  bumping this issue.

Additionally, I realized that the colors for "View timeseries alignment" represents the different modalities. Can there be a legend added that indicates this? 

![Screenshot 2024-07-23 at 1 23 14 PM](https://github.com/user-attachments/assets/fed7d297-ed09-4e0b-b018-aed9425ce8e7)

**Comment by magland** [comment]
@tabedzki I have made the following changes:

The bottom horizontal line on the timeseries plots is now colored 'lightgray' -- let me know if that works for you.

The channels are now colored by default, but you can turn that off with a checkbox.

For the "view timeseries alignment" legend - can we make that a separate issue? And I think that will be low priority.

**Comment by tabedzki** [comment]
HI Jeremy, thank you for the quality of life updates. Those changes look great!
I can make the legend a separate issue.
