### ISSUE TITLE
acquisition entries not appearing

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#186]
This may have to due with the sheer number of them (51)

https://neurosift.app/?p=/nwb&url=https://api.dandiarchive.org/api/assets/4f821f30-01c0-4a8a-a7fc-9144bc0019a5/download/&dandisetId=000020&dandisetVersion=0.210913.1639

<img width="862" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/961868b0-cf00-4079-a8dd-9c7d9b4b0f96">

I am also seeing `Error: Data for /specifications/core/2.2.4/namespace is not a string` in the dev console.

This is a pretty old NWB file, so it may not have all the latest best practices and features

**Comment by magland** [comment]
Yeah, there was a problem parsing the specifications. Instead of throwing an exception I now just log a warning. So it should be working now.
