### ISSUE TITLE
Issue: EphysSummary does not work on data from NeuroConv

### ISSUE THREAD

**Issue by tabedzki** [flatironinstitute/neurosift#191]
Using Neuroconv, I've converted a SpikeGLX folder into a NWB folder. When using the NeuroSift tool through the NWB Guide I am unable to view the electrical series through the summary view plugins.

 - Is this due to the electrical series name within the NWB file?
 - Is there a way to specify in the NWB file that this should be usable via the EphysSummary/how do we fix the plugin usage?
 - Where can I find the list of all available widgets/plugins for Neurosift? I couldn't find a list on any documentation
 
 Thanks in advance

![Screenshot 2024-07-16 at 9 19 58 AM](https://github.com/user-attachments/assets/27756151-5f9e-4a94-a7b8-a0ce3e683d3f)

![Screenshot 2024-07-16 at 9 20 23 AM](https://github.com/user-attachments/assets/3a9e24cc-c734-4136-bd57-84fd136f10f2)

**Comment by magland** [comment]
@tabedzki The EphysSummary links are not supposed to be showing up when using NS within GUIDE. That's because Dendro-dependent views require that the data be on DANDI. Can you confirm... is this being viewed from within GUIDE? Or are these datasets on DANDI?

**Comment by magland** [comment]
@CodyCBakerPhD @garrettmflynn could you confirm which host NWB files are being served on for the neurosift embedded in GUIDE? Is it `http://localhost:[port]`? If so I'm surprised that the EphysSummary buttons are showing up. NS tries to detect whether the NWB file is being served locally.

**Comment by CodyCBakerPhD** [comment]
The URL contained in the iframe is `https://flatironinstitute.github.io/neurosift/?p=/nwb&url=${this.url}` (from https://github.com/NeurodataWithoutBorders/nwb-guide/blob/main/src/electron/frontend/core/components/Neurosift.js#L89)

The GET and POST methods on the local Flask server are defined here: https://github.com/NeurodataWithoutBorders/nwb-guide/blob/main/src/pyflask/namespaces/neurosift.py#L42

which use a base URL of `http://127.0.0.1:${port}` (from https://github.com/NeurodataWithoutBorders/nwb-guide/blob/2da6359136e2b622c9b763fc816d528c12c06234/src/electron/frontend/core/server/globals.ts#L11)

**Comment by tabedzki** [comment]
@magland  I am using the NWB Guide locally and have not uploaded any data to DANDI for use with NeuroSift.

**Comment by magland** [comment]
Thanks @CodyCBakerPhD for that information.

@tabedzki Could you please try now? In GUIDE the EphysSummary links are not expected to show up because Dendro views are not supported unless the data are on a remote server. (We could explore the possibility of enabling them locally as well, but that will require some thought).

**Comment by tabedzki** [comment]
@magland I can confirm that the EphysSummary does not appear now when using a locally provided file.

![Screenshot 2024-07-19 at 1 03 39 PM](https://github.com/user-attachments/assets/fbaba8c8-ef05-4829-84cb-177fb138c721)

**Comment by tabedzki** [comment]
@magland  since it no longer shows locally, should we close this issue?
