### ISSUE TITLE
Request: display units of measurement on y axis of SpatialSeries timeseries plot

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#192]
https://neurosift.app/?p=/nwb&url=https://api.dandiarchive.org/api/assets/5e9e92e1-f044-4aa0-ab47-1cfcb8899348/download/&dandisetId=000003&dandisetVersion=0.230629.1955&tab=neurodata-items:neurodata-item:/acquisition/position_sensor0|SpatialSeries@view:X/Y|/acquisition/position_sensor0

![image](https://github.com/user-attachments/assets/6abd3425-5f0d-4c5c-b914-e3a8f16bd7b0)

The X/Y plot correctly shows the units as meters, but the time series plot above it does not. Could we add "meters" to the y axis label?

**Comment by magland** [comment]
This has been implemented.
