### ISSUE TITLE
Adding a legend for "view timeseries alignment"

### ISSUE THREAD

**Issue by tabedzki** [flatironinstitute/neurosift#196]
The colors for "View timeseries alignment" represents the different modalities as defined [here](https://github.com/flatironinstitute/neurosift/blob/main/gui/src/app/pages/NwbPage/TimeseriesAlignmentView/TimeseriesAlignmentView.tsx#L184-L215). Can a legend be added to indicate the color scheme?

![Screenshot 2024-07-23 at 1 23 14 PM](https://github.com/user-attachments/assets/fed7d297-ed09-4e0b-b018-aed9425ce8e7)

**Comment by magland** [comment]
Looking at this more carefully, I don't think a legend is needed. You can see the types in the text label

[ElectricalSeries], [TimeSeries], [SpatialSeries], etc.

**Comment by tabedzki** [comment]
When one has multiple modalities, I agree. When I initially was generating the NWB files, I had no ElectricalSeries leaving me with just a red and grey. Because two series were red, I thought that the data was somehow "wrong" due to the common meaning of red meaning incorrect.

Is there a way that we can adjust that, or as an alternate, highlight the modality in a textbox when one hovers above the item to prevent such confusion?

**Comment by magland** [comment]
Good point about the red color. And yeah, a tooltip is certainly possible.

Do you want to take a crack at it? Here's the source file
https://github.com/flatironinstitute/neurosift/blob/main/gui/src/app/pages/NwbPage/TimeseriesAlignmentView/TimeseriesAlignmentView.tsx

The function that determines color is getColorForNeurodataType

For tooltip, you can put a title prop on the top-level div of TAItemView

Not sure if you are familiar with typescript or have a desire to learn this...

Here's the instructions for the dev env: https://github.com/flatironinstitute/neurosift/blob/main/doc/development_environment.md
