### ISSUE TITLE
Error while showing `ElectricalSeries` in local NWB file

### ISSUE THREAD

**Issue by weiglszonja** [flatironinstitute/neurosift#198]
I have troubles with opening `ElectricalSeries` data in Neurosift from NWBGuide. I'm not sure what is causing this issue, here is a screenshot of the error:

<img width="1280" alt="Screenshot 2024-07-30 at 11 29 35" src="https://github.com/user-attachments/assets/ad30c745-cb76-4419-9287-490537fd5cd5">

@magland do you have any suggestions how to fix this?

**Comment by magland** [comment]
Should be fixed now!

**Comment by weiglszonja** [comment]
Ah great, thank you so much!
