### ISSUE TITLE
separate out channels

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#20]
![image](https://github.com/flatironinstitute/neurosift/assets/844306/d31b6f53-839e-4202-ab9a-f4d908cf4d32)

It is common when viewing many traces to apply offsets to each trace so that you can see them individually. It would be great to have a checkbox that allows for this view. See the corresponding logic in NWB Widgets [here](https://github.com/NeurodataWithoutBorders/nwbwidgets/blob/62e4ad2c39e7da7aabb6c1210fcac4f0ef27b41e/nwbwidgets/timeseries.py#L405-L439).

**Comment by bendichter** [comment]
Once you have that, it would be great to be able to select a 

It would also be great to be able to navigate up and down through channels. This will be needed for example in Neuropixel recordings, where there are more channels than can reasonably fit in a window all at once

**Comment by bendichter** [comment]
https://flatironinstitute.github.io/neurosift/#/nwb?url=https://dandiarchive.s3.amazonaws.com/blobs/8d8/57c/8d857c1c-1bc3-48ac-ad59-266ea7eb9a79

This file has 384 ElectricalSeries channels, yet only 5 of them are visible in the viewer

<img width="1295" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/c4ca09a8-505f-4ac4-bc7d-a295abd04720">

**Comment by bendichter** [comment]
Yes. There is a "group and order" controller widget on the left. This controls the grouping and the order within that grouping. Honestly, I have found that the grouping is far more useful than the ordering, so if you want to implement something quickly I'd recommend focusing on that. Though I suppose that could go in a separate issue

**Comment by magland** [comment]
@bendichter How am I going to find the electrode information (e.g., the group)

Here's what I see:

![Image](https://github.com/flatironinstitute/neurosift/assets/3679296/370d031d-f565-447d-9aa8-4f31ba168086)

Will it alway be in General -> extracellular_ephys -> electrodes? I don't see any pointer to that...

**Comment by bendichter** [comment]
@magland this is where things get tricky. 

> Will it alway be in General -> extracellular_ephys -> electrodes? I don't see any pointer to that...

The pointer is ElectricalSeries/electrodes.table, which is a link to the electrodes table. It will almost always be at /general/extracellular_ephys/electrodes, though technically it could be other places. `/general/extracellular_ephys/electrodes` is a `DynamicTable`, and should be thought of as a table where each dataset represents a column. You'll need to infer the categorical variables for grouping. These columns are dynamic, and can change from dataset to dataset, so they cannot be hard-coded.

This general pattern will need to be repeated for `RoiResponseSeries`, which is associated with a `PlaneSegmentation` table through a dataset called `.rois`. The one difference is that `PlaneSegmentation` does not have a set place like the electrodes table does, so you are better off following the link in `.electrodes` and `.rois` than using the hard-coded path.

**Comment by magland** [comment]
@bendichter Here's the current state of this widget

![Image](https://github.com/flatironinstitute/neurosift/assets/3679296/3c301045-62fc-4caa-9a15-df1f9a5afcb0)

from https://flatironinstitute.github.io/neurosift/#/nwb?url=https://dandiarchive.s3.amazonaws.com/blobs/082/8f8/0828f847-62e9-443f-8241-3960985ddab3

You can control the number of visible channels (discrete set of options) and then use the left/right buttons to set the group of channels in the dataset. There's also a place to specify the degree of separation between the channels. I used the initial chunk of data to estimate the median local stdev of the data, and then used that (multiplied by a factor) to automatically determine a separation corresponding to a user-selected value of 1. The actual separation factor is pretty arbitrary - so I just put a.u.

Haven't yet handled coloring by group. I think I'll make a separate PR for that.

As mentioned in  #52, the above example loads much more efficiently than the other dataset I was working with. It's important that we get to the bottom of that.

**Comment by bendichter** [comment]
Looks good!
