### ISSUE TITLE
[Feature] SpatialSeries x/y spatial plot - provide axes with units

### ISSUE THREAD

**Issue by magland** [flatironinstitute/neurosift#23]
See #3

**Comment by bendichter** [comment]
can we open this back up? There are numbers but no units of measurement shown

**Comment by magland** [comment]
Thanks, it now shows the units.

![Image](https://github.com/flatironinstitute/neurosift/assets/3679296/23bec231-539a-40ba-9bf8-f6c52dea1164)

**Comment by bendichter** [comment]
Can we please re-open? The rodent is not running 100 meters. I think this data needs to be multiplied by `SpatialSeries.data.conversion`

**Comment by CodyCBakerPhD** [comment]
Just double checking (without digging into underlying code) - is it displaying the value of the `units` attribute set to the `SpatialSeries`? And is the `data` being plotted adjusted by the `conversion` and `offset` values?

**Comment by CodyCBakerPhD** [comment]
> actual = conversion * data + offset

Yes sir! Thanks

This will apply to every descendent of a TimeSeries by the way

**Comment by CodyCBakerPhD** [comment]
@magland Nice catch, I'll dig in a little more. If this is DANDI set `000003` (hard to tell just from asset blob) then this is indeed a bug

The current state of that [source code](https://github.com/catalystneuro/buzsaki-lab-to-nwb/blob/master/buzsaki_lab_to_nwb/utils/neuroscope.py#L198-L208) used for the conversion at the time (not guaranteed to be the exact state it was converted with), indicates the conversion value should have been `np.nan`, though the `unit` should have also be overridden such that `unit="a.u."` to properly indicate that

**Comment by bendichter** [comment]
Paging (aka sharding) may help with this but needs to be tested

**Comment by magland** [comment]
> Paging (aka sharding) may help with this but needs to be tested

Maybe you commented on the wrong thread?

**Comment by magland** [comment]
Closing since, as far as I can tell, the conversion is working (and there's a problem with the nwb file in the above case)

**Comment by CodyCBakerPhD** [comment]
Not that it's a test of the conversion factor specifically (ElectricalSeries will be the best explicit example of that) but here's a newer (properly) converted example from that lab

https://flatironinstitute.github.io/neurosift/#/nwb?url=https://dandiarchive.s3.amazonaws.com/blobs/3f6/47b/3f647b17-8535-4e4a-a75d-17011238ebf7
DANDI set: 000552
sub-e13-16f1/sub-e13-16f1_ses-e13-16f1-210302_behavior+ecephys.nwb

![image](https://github.com/flatironinstitute/neurosift/assets/51133164/b100c077-1276-409d-9950-75319cf5e699)
