### ISSUE TITLE
[Feature] SpatialSeries: click on x/y plot to jump to nearest timepoint

### ISSUE THREAD

**Issue by magland** [flatironinstitute/neurosift#25]
From Ben: For standard timeseries visualizations, you can click on the plot and the selected time will jump to the time of that x coordinate. Would it be possible to enable a similar feature for the x vs. y plot where when you click on the plot if that is near a line segment it will jump to the time that this position occurred?

See #3

**Comment by magland** [comment]
This is now working.

Here's an example: https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://dandiarchive.s3.amazonaws.com/blobs/c86/cdf/c86cdfba-e1af-45a7-8dfd-d243adc20ced

@bendichter

**Comment by bendichter** [comment]
Wow, this is great!
