### ISSUE TITLE
handle time series with irregular timestamps

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#27]
When TimeSeries (and its descendents) are irregularly sampled, the user can opt to indicate the times with a array of `timestamps`, in which case they omit `starting_time` and `starting_time.rate`.

This causes an Error currently:

<img width="1471" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/ba06ce2f-5ae8-481a-a2fa-c24f0c17e642">

**Comment by bendichter** [comment]
As you can see here, this object does indeed have timestamps defined:

<img width="648" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/d81e217f-540a-4c57-8cb7-7495ac90e10c">

**Comment by magland** [comment]
It's going to be pretty difficult to deal with the irregular timestamps case, especially for larger datasets. Suppose we are viewing a range [t1, t2]. How do we know where to look in the array for the data? We'd need to first read from the timestamps array. Not so easy. I'm going to have to think about how to handle this case.

**Comment by bendichter** [comment]
Yes, we had to deal with this in NWB Widgets as well.

The `bisect` method can help reduce the number of reads needed, e.g. https://github.com/NeurodataWithoutBorders/nwbwidgets/blob/d62bed037e24c75f8a9215b8f0ab81e975763700/nwbwidgets/utils/timeseries.py#L120-L150

**Comment by magland** [comment]
@bendichter This is now working.

See processing/behavior -> OpenFieldPosition_Old_position/OpenFieldPosition_Old_twhl_norm_spatial_series

from https://flatironinstitute.github.io/neurosift/#/nwb?url=https://dandiarchive.s3.amazonaws.com/blobs/be4/594/be4594ef-f0db-43b4-b4fa-823927ee3b40

**Comment by bendichter** [comment]
Looks great!
