### ISSUE TITLE
NWB: render trials table

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#29]
https://flatironinstitute.github.io/neurosift/#/nwb?url=https://dandiarchive.s3.amazonaws.com/blobs/c86/cdf/c86cdfba-e1af-45a7-8dfd-d243adc20ced

It would be great to have a viewer for `DynamicTable` objects, and in particular the trials table at `/intervals/trials`. 

<img width="663" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/7da693e8-756d-45a2-9a1a-26966689943c">

In NWB Widgets, in addition to a simple tabular view, we also have this widget, which can be used to plot rows of the table against each other:

https://github.com/NeurodataWithoutBorders/nwbwidgets/blob/d62bed037e24c75f8a9215b8f0ab81e975763700/nwbwidgets/dynamictablesummary.py#L11

**Comment by magland** [comment]
Closing because we now provide a view for DynamicTable. It doesn't have the ability to "plot rows of the table against each other", but that could be opened as a separate issue.
