### ISSUE TITLE
[Feature] NWB: Plot spatial series as x vs y

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#3]
The x and y by time plot is good. Would it be possible to have a second plot type for position series that is plotting x vs y for a given time segment? Even better if the color of the line indicates the time within the segment

**Comment by magland** [comment]
@bendichter 

When viewing SpatialSeries neurodata objects, you can a split panel, with the upper panel a timeseries plot (as before) and the lower panel the spatial plot for the visible time segment. It has color based on the time within that window. There is also a red marker for the currently selected time. There is also now a play button on the left control panel so you can see the animal moving around -- and you can control the playback speed.

For example:
https://flatironinstitute.github.io/neurosift/#/nwb?url=https://dandiarchive.s3.amazonaws.com/blobs/c86/cdf/c86cdfba-e1af-45a7-8dfd-d243adc20ced
/acquisition/position_sensor0

![image](https://github.com/flatironinstitute/neurosift/assets/3679296/7803bc77-29b1-440f-987d-b83d25ed1ab5)

**Comment by bendichter** [comment]
This is great! A few nit-picky requests:

1. If you use a yaml to design your own dashboard, can you choose between these views and/or configure them the way you want? You end up with a kind of awkwardly fat window for x vs y when you stack multiple traces together. It might be nice to horizontally stack windows that don't have time on the x axis (e.g. video).
2. Can you provide axes with units or at least a floating scale bar for the x vs y plot?
3. Often two sensors are used to calculate heading direction. Is there a way to view both in the same x vs y plot?
4. For standard timeseries visualizations, you can click on the plot and the selected time will jump to the time of that x coordinate. Would it be possible to enable a similar feature for the x vs. y plot where when you click on the plot if that is near a line segment it will jump to the time that this position occurred?

**Comment by magland** [comment]
Thanks, I have split those out into individual feature requests and I will close this issue.
