### ISSUE TITLE
for time series, toggle between line and scatter plot

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#31]
In some cases, it is useful to know exactly when samples occurred. Would it be possible to have a toggle that switches timeseries viewer from line plot mode to scatter plot mode?

**Comment by magland** [comment]
There's now a question mark icon that opens a dialog box that shows the keyboard shortcuts. One of the shortcuts is "m" which toggles between line and marker.



![Image](https://github.com/flatironinstitute/neurosift/assets/3679296/48220cfa-b5a1-4455-8aa9-18750f161c5f)
