### ISSUE TITLE
suggestion: use Project to prioritize issues

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#32]
Projects lets you order Issues

**Comment by magland** [comment]
I've never used projects before. Would you suggest Table, Board, or Roadmap?

**Comment by CodyCBakerPhD** [comment]
We use Tables for the most part - here are some examples (I believe they should be publicly viewable)

https://github.com/orgs/NeurodataWithoutBorders/projects/7/views/12

**Comment by CodyCBakerPhD** [comment]
It's also pretty easy to setup GitHub action workflows to automatically post issues/PRs to the projects

See https://github.com/catalystneuro/neuroconv/blob/main/.github/workflows/add-to-dashboard.yml for one example of that

**Comment by magland** [comment]
Thanks, I'll take a look.

**Comment by magland** [comment]
I have set up this project: https://github.com/orgs/flatironinstitute/projects/4

And I will work on setting up the gh action

**Comment by magland** [comment]
@CodyCBakerPhD I tried to set up the workflow action (copied your example and changed a couple fields), but am getting the following error. Any ideas?

```
Run leonsteinhaeuser/project-beta-automations@v1.2.1
  with:
    gh_token: ***
    organization: flatironinstitute
    project_id: 4
    resource_node_id: I_kwDOJvD6Zc5rO[2](https://github.com/flatironinstitute/neurosift/actions/runs/5521158695/jobs/10068850785#step:2:2)FJ
    operation_mode: status
Run echo "***" | gh auth login --with-token
  echo "***" | gh auth login --with-token
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
Run /home/runner/work/_actions/leonsteinhaeuser/project-beta-automations/v1.2.1/entrypoint.sh "organization" "status" "flatironinstitute" "[4](https://github.com/flatironinstitute/neurosift/actions/runs/5521158695/jobs/10068850785#step:2:4)" "I_kwDOJvD6Zc[5](https://github.com/flatironinstitute/neurosift/actions/runs/5521158695/jobs/10068850785#step:2:5)rO2FJ" ""
  /home/runner/work/_actions/leonsteinhaeuser/project-beta-automations/v1.2.1/entrypoint.sh "organization" "status" "flatironinstitute" "4" "I_kwDOJvD[6](https://github.com/flatironinstitute/neurosift/actions/runs/5521158695/jobs/10068850785#step:2:6)Zc5rO2FJ" ""
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GITHUB_TOKEN: ***
gh: Field 'projectNext' doesn't exist on type 'Organization'
Variable $number is declared by anonymous query but not used
gh: Field 'addProjectNextItem' doesn't exist on type 'Mutation'
Variable $project is declared by anonymous mutation but not used
Variable $resource_id is declared by anonymous mutation but not used
jq: error (at /tmp/api_response.json:0): Cannot iterate over null (null)
jq: error (at /tmp/api_response.json:0): Cannot iterate over null (null)
accepts 1 arg(s), received 25
```

**Comment by CodyCBakerPhD** [comment]
Hm.. Such a simple workflow, not sure what could fail differently from us as long as you have the `MY_GITHUB_TOKEN` secret set, and you generated it with the right scoped permissions, and have those organization permissions yourself...

I know the PyNWB team uses a separate workflow than us, might be worth checking out: https://github.com/NeurodataWithoutBorders/pynwb/blob/f8041c4e2e7a1392e2383353a74c0f548ca4c050/.github/workflows/project_action.yml

Might need to ask @rly how to set the secrets though

**Comment by magland** [comment]
I suspect I don't have the approprioate org permissions. I'm not going to worry about this for now... I'll just manually move issues to the project.
