### ISSUE TITLE
show where data is defined

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#39]
For data that is irregularly sampled, sometimes there are large gaps. For example, here this particular maze was run at the beginning and the end:

![image](https://github.com/flatironinstitute/neurosift/assets/844306/01e71e12-c587-49c4-b3c7-ab6552593f00)

![image](https://github.com/flatironinstitute/neurosift/assets/844306/ffdc4fbb-3c92-46bc-9a28-350a7bb9efb3)

It is difficult to know where this data is defined. It would be nice if there were markers on the navigation slider indicating where data is defined. 

An alternative approach would be in the future to break disjoint timeseries like these into two separate objects.

**Comment by CodyCBakerPhD** [comment]
I believe this has been solved with the 'temporal alignment' feature, which should show gaps in timespans?

**Comment by magland** [comment]
> I believe this has been solved with the 'temporal alignment' feature, which should show gaps in timespans?

Yes, it may not be what Ben was originally asking for, but I'm going to close this for now.
