### ISSUE TITLE
Move away from using hash (#) character in URL

### ISSUE THREAD

**Issue by magland** [flatironinstitute/neurosift#47]
In some browsers, when you paste in a new url, it doesn't refresh if the string before the # is unchanged. So we should move to a scheme of the form

https://flatironinstitute.github.io/neurosift?p=/nwb&url=...

(By nature of gh pages hosting we can't extend the main path)

**Comment by magland** [comment]
This has been completed.

https://flatironinstitute.github.io/neurosift#/nwb?url=https://dandiarchive.s3.amazonaws.com/blobs/082/8f8/0828f847-62e9-443f-8241-3960985ddab3
now redirects to
https://flatironinstitute.github.io/neurosift?p=/nwb&url=https://dandiarchive.s3.amazonaws.com/blobs/082/8f8/0828f847-62e9-443f-8241-3960985ddab3

Technically this should be updated on DANDI, but maybe I don't want to delay the existing PR.

**Comment by CodyCBakerPhD** [comment]
> Technically this should be updated on DANDI, but maybe I don't want to delay the existing PR.

If it's a problem with the DANDI archive, could you raise an issue about it just so they're aware?

**Comment by magland** [comment]
> If it's a problem with the DANDI archive, could you raise an issue about it just so they're aware?

Okay, I opened a new PR
