### ISSUE TITLE
[Documentation] Instructions and example for making plugins

### ISSUE THREAD

**Issue by CodyCBakerPhD** [flatironinstitute/neurosift#53]
Hey @magland, thanks for all your amazing hard work on this!

I'm very excited by #49 so as a follow-up I was wondering if you could put together some quick and dirty documentation (README.md would be fine) for how someone unfamiliar with the package could make such a plugin and get it working in their browser (would they need to run a local host? fork the project to host on their own pages? could there be some kind of dynamic import from the main neurosift pages host if the plugin is available on another GitHub project?)

**Comment by magland** [comment]
@CodyCBakerPhD I put in some instructions on creating a neurosift development environment. You can run a dev server on localhost. If you want to make changes and deploy them to your own github-pages hosted site, that's also possible, but I didn't provide instructions. See the bottom of the [README.md](https://github.com/flatironinstitute/neurosift/blob/main/README.md#developers).

I also created a HelloWorld view plugin that hijacks the LabeledEvents neurodata_type. You can find an example of that type here:
https://flatironinstitute.github.io/neurosift/#/nwb?url=https://dandiarchive.s3.amazonaws.com/blobs/8cf/38e/8cf38e36-6cd8-4c10-9d74-c2e6be70f019
And find the object in processing/behavior/RewardEventsLinearTrack
If you click on that, you should see the HelloWorld view, which just displays the contents of the hdf5 group.

![Image](https://github.com/flatironinstitute/neurosift/assets/3679296/07e41184-c392-467e-90e6-e9ff478ef15d)
