### ISSUE TITLE
ElectricalSeries - plot axes value range and units

### ISSUE THREAD

**Issue by CodyCBakerPhD** [flatironinstitute/neurosift#55]
Similar to #23 but for ElectricalSeries and LFP

A seen in screenshot

![image](https://github.com/flatironinstitute/neurosift/assets/51133164/4d5607bb-8619-4ef8-84bb-74ded77d0457)

would be great to get visible voltage range to test proper conversion factor + offset scaling (offset will be zero most of the time, I know - will try to find a dandi set where it's not)

from

https://flatironinstitute.github.io/neurosift/#/nwb?url=https://dandiarchive.s3.amazonaws.com/blobs/295/36e/29536e2e-1178-41c2-85ef-a27536a05c92
DANDI set: 000552
sub-e15-13f1/sub-e15-13f1_ses-e15-13f1-220117-raw_ecephys.nwb

**Comment by CodyCBakerPhD** [comment]
Also notice: I noticed the 'view' on the left there says 'SpatialSeries' even though it's LFP in processing/ecephys/LFP

**Comment by magland** [comment]
The y axis values should be displaying now.
