### ISSUE TITLE
Support ImageSeries visualization with external_file pointer to .avi file

### ISSUE THREAD

**Issue by magland** [flatironinstitute/neurosift#60]
Here's an example where you can visualize the external video associated with an ImageSeries within neurosift when browsing the nwb file.

https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://dandiarchive.s3.amazonaws.com/blobs/8cf/38e/8cf38e36-6cd8-4c10-9d74-c2e6be70f019&dandi-asset=https://api.dandiarchive.org/api/dandisets/000568/versions/0.230705.1633/assets/9fc5a60e-af09-4099-ac22-ee54211f55e4/

acquisition -> ImageSeriesTrackingVideo1

Notice that the additional query parameter `dandi-asset` is needed to be able to locate the .avi asset based on the relative path in the external_file dataset of the ImageSeries.

The internal steps here are:
* Hit the dandi API for the path of the asset within the dandiset
* Contruct the video path from the asset path and the external file relative path
* Hit the dandi API for the list of all assets
* Find the asset in that list that matches the video path and obtain that asset ID
* Hit the API a third time to obtain the blob URL for the video asset
* HEAD the video blob to get the ETag
* Look up with converted.mp4 in the external bucket where all the .avi->mp4 are cached
* Show the video

This opens up possibilities for synchronizing the video with the other data objects in the nwb file (stimulus, spiking, etc).

This is related to #59

![Image](https://github.com/flatironinstitute/neurosift/assets/3679296/0b1fa207-0a72-488c-9ced-0e18fca105ea)

@bendichter @CodyCBakerPhD @satra

**Comment by satra** [comment]
if we modified the parameters to `asset_url`, i'm assuming you can get everything from it, right? the blob url is in that metadata.

**Comment by CodyCBakerPhD** [comment]
Looks amazing to me!

The very fact that I can get something like

![image](https://github.com/flatironinstitute/neurosift/assets/51133164/3804ac99-0a74-473e-970a-8f98c84f95af)

within seconds is groundbreaking for exploratory analysis of these files

Minor improvements, some of which you allude to:

i) harness `starting_time`/`rate`/`timestamps` of the ImageSeries in the video viewer so they can display aligned with the other data streams
ii) couple the general purpose 'play' button with the one on the video so I can truly see them match frame-by-frame (I could only get them kind of 'close' manually

**Comment by magland** [comment]
> if we modified the parameters to `asset_url`, i'm assuming you can get everything from it, right? the blob url is in that metadata.

That's correct. I'll work on supporting `https://flatironinstitute.github.io/neurosift?/nwb&dandy-asset=...` without the url. Then could DANDI GUI link to that?

**Comment by magland** [comment]
> i) harness `starting_time`/`rate`/`timestamps` of the ImageSeries in the video viewer so they can display aligned with the other data streams ii) couple the general purpose 'play' button with the one on the video so I can truly see them match frame-by-frame (I could only get them kind of 'close' manually

Thanks, that sounds like a good plan.

**Comment by bendichter** [comment]
@magland 

> https://flatironinstitute.github.io/neurosift?/nwb&dandy-asset=...
that's `dandi` not `dandy` :-)

**Comment by magland** [comment]
@satra, you can now pass in the dandi-asset parameter without the url, and it will automatically resolve. As in the following.

https://flatironinstitute.github.io/neurosift/?p=/nwb&dandi-asset=https://api.dandiarchive.org/api/dandisets/000568/versions/0.230705.1633/assets/9fc5a60e-af09-4099-ac22-ee54211f55e4/

However, if you want to provide both `dandi-asset` and `url` then the page will load more quickly, and it will also have a fallback in case the dandi API is down or slow.

**Comment by satra** [comment]
i have sent a PR here: https://github.com/dandi/dandi-archive/pull/1655 and in the deploy preview it seems to do the right thing. in brainzzz dandiset, i can see the neurosift link generate:

https://flatironinstitute.github.io/neurosift?p=/nwb&url=https://dandi-api-staging-dandisets.s3.amazonaws.com/blobs/c1b/1a7/c1b1a722-4ba3-4b3c-898a-3017b3861967&dandi-asset=https://api-staging.dandiarchive.org/api/dandisets/208295/versions/0.230427.0112/assets/adfa6f50-bcde-4322-8f98-df26f102371a

**Comment by magland** [comment]
Thanks @satra !
