### ISSUE TITLE
PlaneSegmentation/TwoPhotonImage - investigate orientation

### ISSUE THREAD

**Issue by magland** [flatironinstitute/neurosift#64]
It also finally enables direct side by side comparison against frames from the TwoPhotonSeries

When I do that to `000054` I get

![image](https://github.com/flatironinstitute/neurosift/assets/51133164/f56d126b-baa4-4c05-8457-18fae9fd1ab0)

which makes me wonder if perhaps there is some flipping/transposing going on, and if so is it an issue in the data or is it perhaps the image in NeuroSift that needs rotation? (or even rotation buttons on both windows just for good measure and convenience might be nice)

_Originally posted by @CodyCBakerPhD in https://github.com/flatironinstitute/neurosift/issues/21#issuecomment-1638666295_

**Comment by CodyCBakerPhD** [comment]
I think rotation buttons were added to alleviate this

**Comment by magland** [comment]
> I think rotation buttons were added to alleviate this

Yes I believe so. I am closing this, but if not resolved, please reopen.
