### ISSUE TITLE
TwoPhotonSeries - example takes too long to load...

### ISSUE THREAD

**Issue by magland** [flatironinstitute/neurosift#65]
https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://dandiarchive.s3.amazonaws.com/blobs/a65/6b4/a656b41f-99f7-49e0-a13e-1b283b97a002

See https://github.com/flatironinstitute/neurosift/issues/21#issuecomment-1638666295

**Comment by magland** [comment]
The problem here is the chunking pattern for the TwoPhotonSeries/data dataset

```python
import fsspec
import h5py

s3_url = 'https://dandiarchive.s3.amazonaws.com/blobs/a65/6b4/a656b41f-99f7-49e0-a13e-1b283b97a002'

fs = fsspec.filesystem("http")

f = fs.open(s3_url, "rb")
file = h5py.File(f)
print('Getting data object')
x = file['acquisition']['TwoPhotonSeries1']['data']
print(f'Shape of data: {x.shape}')
print(f'Chunking:', x.chunks)
print(f'Compression:', x.compression)
print(f'Compression opts:', x.compression_opts)
```

```
# output
Getting data object
Shape of data: (40000, 248, 440)
Chunking: (2254, 14, 14)
Compression: gzip
Compression opts: 4
```

With this scheme, you need to do more than 500 requests to the bucket in order to view even just a single image. This is similar to the ElectricalSeries chunking issue, but this is more problematic because you usually want to see the entire image (whereas with ElectricalSeries it's okay to view a few channels at a time).

@bendichter @CodyCBakerPhD I guess this is a tradeoff, depending on whether you look at entire images, or the traces over time. It almost feels like there should be two copies of the data stored in the file to accomplish remote access in both scenarios.

**Comment by magland** [comment]
A follow up here. Even beyond the problem of making > 500 requests for getting just one slice... the amount of data that needs to be downloaded to render a single slice is on the order of 

2254*248*440 bytes ~ 245 MB

(Of course, once you have the first slice, you can get the next couple thousand for free)

**Comment by CodyCBakerPhD** [comment]
I'll admit that chunking is not ideal for most access patterns, I'll draft a modification of our default shaper specific to 2P data that strikes a better balance
