### ISSUE TITLE
NWB: DynamicTable

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#67]
NWB uses the `DynamicTable` type to store tabular data, and should be displayed as a table. This comes up most often with the `TimeIntervals` neurodata type, which is a subclass of `DynamicTable`. Currently, `TimeIntervals` objects are displayed using the default raw format:

<img width="1284" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/3bca71a6-f71e-4ff2-973d-6fe3ad58be38">

https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://dandiarchive.s3.amazonaws.com/blobs/368/fa7/368fa71e-4c93-4f7e-af15-06776ca07f34

Instead, it should be a table with the headers defined by the `colnames` dataset (this gives the order of the headers) and the values given by the values of the datasets that have those names.

`DynamicTable` objects are usually small enough to read entirely into RAM and render in entirety. The exception would be `Units` and `PlaneSegmentation`, which both already have their own visualizations

**Comment by magland** [comment]
@bendichter could you provide an example or two? I can't find any.

**Comment by bendichter** [comment]
This is great! I really like the time view. I think it's fine to have that as the default.

This is kind of minor, but I don't know if TimeSeries is the best term here. "TimeSeries" is a fundamental type in NWB that a lot of types derive from (e.g. `ElectricalSeries`, `RoiResponseSeries`, `SpatialSeries`). The `TimeSeries` neurodata type provides a standard structure for data sampled through time. These types all consist of `data` and either `timestamps` or `rate` and `starting_time`, with metadata specific to that modality. `TimeIntervals` is actually in the `DynamicTable` family, and does not have this structure. So while it is certainly through _time_, I don't know if I would call it a _series_. How about renaming the tab to "Over Time" or something like that?

For the time view, it would be great to have a dropdown that had all of the (inferred) categorical columns in the table and when you select one of those labels it would color all of the segments by that

It would be nice to provide the descriptions of the columns somehow. Maybe as hover text over the column names?

**Comment by magland** [comment]
I changed the name to "time plot"

I didn't implement the dropdown yet. I'll open a separate issue for that. For now I am using the [most likely candidate] for a categorical value. It looks like this

![Image](https://github.com/flatironinstitute/neurosift/assets/3679296/a530dc3d-4846-440f-9da8-eda45600b042)

I'll open a separate issue for providing the column descriptions.
