### ISSUE TITLE
time intervals table - show column descriptions on hover

### ISSUE THREAD

**Issue by magland** [flatironinstitute/neurosift#69]
See https://github.com/flatironinstitute/neurosift/issues/67#issuecomment-1640071377

The description is an attribute of each column's dataset

**Comment by bendichter** [comment]
This should apply to all DynamicTables, not just TimeIntervals

**Comment by magland** [comment]
@bendichter this has been implemented

![Image](https://github.com/flatironinstitute/neurosift/assets/3679296/2891987c-19d1-4dd8-8c8e-ad8594966a0a)
