### ISSUE TITLE
Describe caching mechanism being used for preloading the meta data from nwb file

### ISSUE THREAD

**Issue by magland** [flatironinstitute/neurosift#7]

**Comment by CodyCBakerPhD** [comment]
> Of course there is a problem if the nwb file is a draft. We'll need to think about that.

Would a 'refresh' button/command work? DANDI asset metadata does track last time of modification, so such a callback would trigger a re-cache iff time of last cache was before time of most recent modification

**Comment by bendichter** [comment]
Maybe the digest fields could be helpful here?

e.g. 

    "digest": {
        "dandi:sha2-256": "d7f093d21aff638ef8a1b9ee372bafc5d1cc54b17a0155c47b4a31f224fe8d3d",
        "dandi:dandi-etag": "81536fc1f94a5f10351d596fa21a7538-7572"
    },

every NWB file on DANDI has these fields in their metadata. If you are using these as the cache lookup that should handle cache validation.

source:
https://api.dandiarchive.org/api/dandisets/000149/versions/draft/assets/81169999-c697-4eca-a635-2fd994ac183f/

**Comment by CodyCBakerPhD** [comment]
> Maybe the digest fields could be helpful here?

Yes actually, the `dandi:sha2-256` checksum could be more reliable than the modification time as well as being easier to assert (if the string in the cash is unequal to string returned from latest/triggered API fetch)

**Comment by magland** [comment]
I am now using the ETag for naming the meta nwb file on the neurosift bucket. Closing.
