### ISSUE TITLE
NWB: time grid

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#71]
@h-mayorquin is developing an interesting widget in NWB Widgets that might be valuable here as well: https://github.com/NeurodataWithoutBorders/nwbwidgets/pull/302

When looking at an NWB file, it can be helpful to see all of the TimeSeries objects and view how they align to each other. This is particularly helpful after applying temporal alignment procedures such as TTL pulse detection, to ensure that the resulting temporal offsets are reasonable. It can also be helpful when viewing datasets that contain many short TimeSeries, as is sometimes the case when recordings are stopped and started many times within a single session.

**Comment by magland** [comment]
@bendichter 

Not sure if this is exactly what you had in mind, but there is a new button in the lower left called "View timeseries alignment"

For this example

https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://dandiarchive.s3.amazonaws.com/blobs/8cf/38e/8cf38e36-6cd8-4c10-9d74-c2e6be70f019&dandi-asset=https://api.dandiarchive.org/api/dandisets/000568/versions/0.230705.1633/assets/9fc5a60e-af09-4099-ac22-ee54211f55e4/

it looks like this:

![Image](https://github.com/flatironinstitute/neurosift/assets/3679296/6404a912-f237-4d1b-b823-399bde7730a7)

**Comment by bendichter** [comment]
This looks great!
