### ISSUE TITLE
NWB: render based on neurodata_type

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#72]
from https://github.com/flatironinstitute/neurosift/issues/67#issuecomment-1640038508

> In the main tab, whether or not the object is rendered in "default raw format" is not determined by the object type (e.g., TimeIntervals), but is determined by which top level heading it falls under.

Is there a particular reason you need to do it this way? In general, it is better to make decisions based on neurodata_type, not location. While there are common places for many types, this is actually quite flexible. A `TimeIntervals` object _can_ go in a `ProcessingModule`. A `Units` table also _can_ go in a `ProcessingModule`, and this is the appropriate thing to do in some cases. If you want to render these consistently, it would be better to base visualizations entirely on neurodata_type, not location. Also, if you have an extension that inherits from the generic `NWBDataInterface` and are placed in a `ProcessingModule`, I think it would be best to render this as the default raw format.

**Comment by magland** [comment]
I think there's a couple different questions here: (a) How an object is displayed itself (in a dedicated tab) and (b) How an object appears in the context of its parent object. So for example, right now the "intervals" group expands to a table showing its TimeIntervals child objects as rows in the table, with relevant information for this type of view as the columns. So in this case, the location of the objects affects the presentation...

**Comment by bendichter** [comment]
Oh, I see. OK, I'll close this.
