### ISSUE TITLE
SpatialSeries multiview does not show x-by-y

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#75]
When viewing a spatial series the x-by-y plot is present when viewing the SpatialSeries on its own

<img width="1715" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/c8d6fb18-a647-4612-84cc-953819ae04f2">

but it cannot be viewed in a multi-view:

<img width="1724" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/6108eb7e-9f7a-4adc-8aa0-4e553b1c1768">

Maybe a solution could be to allow the user to select what views they want to bring up. You could offer a multi-select for all types that have multiple views and the user can decide which one(s) they want to display.

source: https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://dandiarchive.s3.amazonaws.com/blobs/f89/c91/f89c9160-056d-4edc-90c6-399dce74d407

**Comment by magland** [comment]
This has been addressed by #78. As you suggested you now have a lot more flexibility in mixing and matching views, and more than one view plugin can be associated with the same neurodata type.
