### ISSUE TITLE
NWB request: filter and sort rows of DynamicTable

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#79]
Non-essential feature, but would be nice to have

In NWB Widgets, the DynamicTable viewer has the ability to sort and filter by each column, e.g.

<img width="1091" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/6178c983-3bd3-4bba-a2b9-dc64c62a57f3">

<img width="943" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/736bd524-7cdd-4c9e-a737-ee35f4ce2472">

<img width="875" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/71ee1801-b14f-4bf2-860d-d7d718e6b179">

<img width="328" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/615fef91-901a-44fe-bba7-03d6868903ff">

<img width="267" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/c8524cbd-7298-4a52-958e-45d00f5abf21">

**Comment by magland** [comment]
I've implemented sorting of columns in DynamicTable. For example, see the units here

https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://dandiarchive.s3.amazonaws.com/blobs/544/745/5447455e-49ec-4ce0-9a64-4cad767bef7b

However, I haven't implemented filtering - that's more challenging from the UI perspective. I am going to hold off on that and propose to close this issue. @bendichter feel free to reopen if filtering by value is a crucial feature.
