### ISSUE TITLE
raw display improvement

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#81]
Right now, all data is within an expansion tab, e.g.

<img width="432" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/4f38ef6f-62d3-484c-a416-fcd5f968919f">

For datasets that are scalars, this seems unnecessary. It would be nice to just read this data and display it without expansion, e.g. 

```
▼ subject | Subject
  age: 256 days
  species: Mus musculus
  etc.
```

**Comment by magland** [comment]
This has been implemented.


![Image](https://github.com/flatironinstitute/neurosift/assets/3679296/d7da3a46-b3c9-4282-98e4-3a48879acd0f)
