### ISSUE TITLE
NWB neurodata type: BehavioralEvents

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#87]
https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://dandiarchive.s3.amazonaws.com/blobs/a93/0bb/a930bb36-4e47-4158-bc61-6d4a8e77ec9b

<img width="792" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/acdec83c-8f78-4a0a-965f-de30ee2f632e">

This is another MultiContainerInterface. I'll create a PR

**Comment by magland** [comment]
@bendichter I don't see a /processing/behavior/BehavioralEvents.response group in that dataset you linked. Maybe you provided the wrong link?

I do see a BehavioralEvents object here (Frank lab dataset):
https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://dandiarchive.s3.amazonaws.com/blobs/645/10d/64510d67-fab1-45ab-abc3-b18c9738412c

And I see this consists of TimeSeries objects. Each timeseries has a timestamps and a data, and the data is of the form `0, 0, 1, 0, 1, 0, 1, ..., 0, 1, 0, 0` So it seems to alternate `0` and `1` with an extra zero at the beginning and the end. Is this always going to be the format? Where can I go to see a description of the BehavioralEvents type?

**Comment by magland** [comment]
BehavioralEvents view has been implemented. Here are some examples

Gillespie et al (2021) Many series, 2 categories (0, 1) Rbeam, Rlight, Rpump, Wbeam, Wlight, Wpump, arm1beam, ... 

https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://dandiarchive.s3.amazonaws.com/blobs/645/10d/64510d67-fab1-45ab-abc3-b18c9738412c&tab=neurodata-item:/processing/behavior/behavioral_events|BehavioralEvents

![Image](https://github.com/flatironinstitute/neurosift/assets/3679296/4fd56218-ab89-450f-8968-40af8a8edb5c)


Example of true/false response:

https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://dandiarchive.s3.amazonaws.com/blobs/dba/4f5/dba4f5a2-0497-4c99-800b-beab999ded30&tab=neurodata-item:/processing/behavior/BehavioralEvents.response|BehavioralEvents&tab-time=223.73317440998176,343.4894932966775,263.48794255314124

![Image](https://github.com/flatironinstitute/neurosift/assets/3679296/8faea292-53a5-4c2f-b6a3-916c5e6962a1)

timestamp_lick and timestamp_reward - only one category "1". You can see the licking after each reward.

https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://dandiarchive.s3.amazonaws.com/blobs/5bb/122/5bb122c4-91ad-4dee-9bd7-6171c201d175&tab=neurodata-item:/processing/behavior/BehavioralEvents|BehavioralEvents&tab-time=726.747348512647,797.6914262994173,726.747348512647

![Image](https://github.com/flatironinstitute/neurosift/assets/3679296/f6ee0e83-041e-44b4-bac8-e16e48b1c280)

Many series (14) - one category "1" delay_start_times, delay_stop_times, go_start_times, go_stop_times, left_lick_times, photostim_start_times, presample_start_times, ...

https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://dandiarchive.s3.amazonaws.com/blobs/b21/4e2/b214e256-3259-48f3-b11e-ec766dfe0031&tab=neurodata-item:/acquisition/BehavioralEvents|BehavioralEvents&tab-time=988.8964941022433,1161.3496320166369,1062.4406013968776

![Image](https://github.com/flatironinstitute/neurosift/assets/3679296/767e7cea-ca27-4006-8e9a-b88437f871b5)

@lfrank @bendichter
