### ISSUE TITLE
[Feature request] Recognize `ndx-events` objects for event times raster plots?

### ISSUE THREAD

**Issue by tuanpham96** [flatironinstitute/neurosift#89]
I got this error when I tried loading an `AnnotatedEventsTable` created with  `ndx-events`. 

> View plugin not found: neurodata-item:/processing/ophys/events|AnnotatedEventsTable

It would be great if `neurosift` can recognize `event_times`  column in event tables (types: `LabeledEvents`, `AnnotatedEventsTable`) created by `ndx-events` for raster plots

**Comment by tuanpham96** [comment]
I'm not certain whether there's an existing dandiset for this yet. Maybe @bendichter knows. 

Here's an example NWB file I generated from modifying the example from [`ndx-events` README](https://github.com/rly/ndx-events)

[ndx-events-example.zip](https://github.com/flatironinstitute/neurosift/files/12216745/ndx-events-example.zip)

**Comment by magland** [comment]
@tuanpham96 

AnnotatedEventsTable is now supported.

You should now see the following:

![Image](https://github.com/flatironinstitute/neurosift/assets/3679296/e85cc868-f32d-4544-b5e0-44d6ff83f76b)

which allows you to get two types of views

(a) A raster plot
(b) A table, with one row per unit

**Comment by magland** [comment]
Thanks @CodyCBakerPhD.

It appears that LabeledEvents does not have an event_times dataset. It has a timestamps dataset.

How would you expect LabeledEvents to be displayed? Raster plot with only one row?

**Comment by tuanpham96** [comment]
@magland thanks for this! I tested and it looks fine for the `AnnotatedEvents` for the time being. It'd be great to also support `LabeledEvents` as well, but since you already opened another issue., should I close this one?

**Comment by magland** [comment]
Glad that's working. Yes, I'll close this issue and we can follow up with #92.
