### ISSUE TITLE
rendering experimenters with space

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#91]
This is pretty minor, but it would be nice to create space between the experimenters.

<img width="502" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/fd21a7a4-4b49-49cf-afdd-18828825bc95">

source: https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://dandiarchive.s3.amazonaws.com/blobs/80d/c44/80dc4460-7652-4b88-97ce-69a7e8be5d60

**Comment by magland** [comment]
This has been fixed.
