### ISSUE TITLE
PSTH / PETH

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#93]
peristimiulus time histogram / peri-event time histogram

Here's an example of the NWB widget for this

<img width="1010" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/ac5eb707-9470-4707-8e69-338ff0cec41e">

Features:
* Select a specific unit (neuron)
* Trial-align spike times based on some event time within the trials table
    * bonus: use any TimeIntervals table or event times from an AnnotatedEvents table
    * bonus: allow user to select multiple trial events to align to and render the PETH plots side by side
* allow user to set before and after window around trial events
* bin and/or smooth spike times. Express firing rate in units of Hz
    * bonus: control parameters of binning or smoothing
* user selects from categorical columns of trials table to group trials. Trials are ordered and colored by the values of that column.
    * bonus: user can multi-select which values to view in that category, controlling which values to include and exclude

source data: https://dandiarchive.org/dandiset/000128/0.220113.0400/files?location=sub-Jenkins

**Comment by magland** [comment]
@bendichter How does this look?

https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://dandiarchive.s3.amazonaws.com/blobs/df3/e3f/df3e3f73-50ab-42b4-8827-82664ddd474a&tab=view:PSTH|/intervals/trials

![Image](https://github.com/flatironinstitute/neurosift/assets/3679296/b95d8378-daea-4dd4-a18b-7704fdd1adc5)

**Comment by CodyCBakerPhD** [comment]
Also would be cool to have an upper bound on the Hz axis scale to get a feel for the value range of the firing rate

**Comment by magland** [comment]
@CodyCBakerPhD there is now a 'select all' checkbox... and now the loading doesn't actually begin until the unit box becomes visible (to prevent overloading for a large number of units)

![image](https://github.com/flatironinstitute/neurosift/assets/3679296/dbe174c9-0198-4ab7-b757-ca1783c36d0c)

**Comment by CodyCBakerPhD** [comment]
Yep, this is a great implementation! I'll raise separate issues for any other ideas over time

**Comment by magland** [comment]
The weirdest thing happened with the issue tracker. The title of this issue showed up as "PSTH / THING" instead of "PSTH / PETH" for just a minute, and I snapped a screenshot of it. Did someone change the title and then switch it back? It's just weird...

![Image](https://github.com/flatironinstitute/neurosift/assets/3679296/a2b55023-e7a3-4ab3-aed2-35e33f8183e3)

**Comment by magland** [comment]
And you'll also notice that "magland" was replaced by "to land" throughout. Is github glitching? Or is someone hacking my browser?

**Comment by bendichter** [comment]
My guess would be some sort of translation layer translating from another language that it is detecting

**Comment by magland** [comment]
Here's another interesting example where the neural responses to wheel movements are very significant

https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://dandiarchive.s3.amazonaws.com/blobs/84b/0c1/84b0c1d5-0ccc-45af-95bf-c35777e3392e&tab=view:PSTH|/processing/behavior/WheelMovementIntervals
