### ISSUE TITLE
experimenter error

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#99]
DANDI has a staging server that we use for test files, e.g. https://gui-staging.dandiarchive.org/dandiset/209725/draft/

When I try to launch neurosift on one of these files through the web UI it starts to work and then I get a blank screen

**Comment by magland** [comment]
This has now been resolved. The issue was that I was expecting a list of strings for experimenter, but it it's just a string for these examples. Most of the time there are try/catch for these rendering operations, but this one field was an exception.
